### ISSUE TITLE
Apache vhost role includes proxypass directives in the :80 vhost which sometimes causes issues with the redirect to https

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/ala-install#110]
If your application uses https, then the apache vhost role creates 2 vhosts, one for port 80, the other for 443, and adds a permanent redirect from 80 to 443. However, it still includes ProxyPass directives in the :80 vhost, which sometimes seem to be executed even when the Redirect is present, resulting in the browser staying on http when it should have redirected to https.

**Comment by ansell** [comment]
Closing this, as we are releasing all new servers using nginx, which doesn't have this issue for HTTPS only servers which use the 301 redirect.
