### ISSUE TITLE
biocache_service_base_url usage inconsistent

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/ala-install#111]
biocache_service_base_url is used inconsistently. e.g. specieslist expects a url to biocache-service and sandbox expects a url to ala-hub.

**Comment by ansell** [comment]
There have been some changes in the past week to the way ``biocache_service_context_path`` in the last week that may have broken ``biocache_service_base_url``, or may have fixed it. Any idea whether this issue has been fixed?
