### ISSUE TITLE
create install for spatial-service and spatial-hub

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/ala-install#113]
spatial-service requires mapping to /ws and /layers-service

**Comment by ansell** [comment]
The current wkhtmltopdf role is currently broken, which is a dependency of spatial in the current ansible scripts. See https://github.com/AtlasOfLivingAustralia/ala-install/issues/138

**Comment by ansell** [comment]
Wkhtmltopdf is being deprecated, so that won't be an issue. The remaining issue I am aware of with the existing ansible scripts for spatial is the postgis script paths, which has an issue opened by someone in the past at https://github.com/AtlasOfLivingAustralia/ala-install/issues/120

**Comment by ansell** [comment]
The installation for this should now be working with two new roles, spatial-service and spatial-hub, added for this purpose.
