### ISSUE TITLE
biocache-hub facets.cache parameter causing errors

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/ala-install#116]
facets.cache parameter should be absent if not configured. If the value is empty instead of missing, it will produce errors in biocache-service logs.

This is the line
https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/biocache-hub/templates/config/config.properties#L78

**Comment by ansell** [comment]
Is it possible to fix this in biocache-hub instead of here? It isn't difficult to check if an ansible variable is defined and not add the line in that case, just wondering where the most appropriate place to fix it is.
