### ISSUE TITLE
biocache-cli role bad configuration

### ISSUE THREAD

**Issue by santiagomrv** [AtlasOfLivingAustralia/ala-install#137]
I get this error when i try to run ansible-playbook using the ale-demo.yml

	TASK [biocache-cli : unjar biocache] *******************************************
	fatal: [vagrant1]: FAILED! => {"failed": true, "msg": "file or module does not exist: /usr/lib/biocache/biocache.zip"}

I had to comment this lines in the /Users/gbif-apple/dev/als-install-andorra/ansible/roles/biocache-cli/tasks/main.yml file and unzip the file manually:

	#- name: unjar biocache
	#  unarchive:
	#    src: /usr/lib/biocache/biocache.zip
	#    dest: /usr/lib/biocache/
	#    remote_src: True
	#  tags:
	#    - biocache-cli

When i do this then the process finish correctly.

Santi!!!

**Comment by santiagomrv** [comment]
Other think that i found it. Once I have the vagrant with all installed, I have realized that i have to change the configuration of /usr/bin/biocache because my virtual machine only has 6GB RAM and we set $JAVA_OPTS with that:

exec "$JAVACMD" $JAVA_OPTS -Xms2g -Xmx2g $BIOCACHE_OPTS -XX:+UseG1GC -Dfile.encoding=UTF8 -Dlog4j.configuration=log4j.xml -Dactors.corePoolSize=8 -Dactors.maxPoolSize=16 -Dactors.minPoolSize=8 -Djava.util.Arrays.useLegacyMergeSort=true

The result of that when we want to run $ biocache is this:

	OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000003f6000000, 17179869184, 0) failed; error='Cannot allocate memory' (errno=12)
	#
	# There is insufficient memory for the Java Runtime Environment to continue.
	# Native memory allocation (malloc) failed to allocate 17179869184 bytes for committing reserved memory.
	# An error report file with more information is saved as:
	# /tmp/hs_err_pid13184.log
	vagrant@ala:/usr/lib/biocache/biocache-store-1.9$ sudo biocache
	OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000003f6000000, 17179869184, 0) failed; error='Cannot allocate memory' (errno=12)

Maybe we could solve this detecting the RAM configuration of the virtual machine and set those values depending on it.

Thanks,
Santi!!

**Comment by santiagomrv** [comment]
My VM has 6GB Ram and if i put -Xms1024m -Xmx1024m, then biocache works well.

**Comment by ansell** [comment]
You can pass the java heap memory options to biocache-cli using ``biocache_opts`` ansible variable, or by manually modifying the ``environmentSetup.sh`` file if you have already deployed

However, we also switched the defaults to 1g, so it may work out of the box for you now.

https://github.com/AtlasOfLivingAustralia/ala-install/blob/ff5870a45cfd0381111fca7868a3bcf2424f2bb0/ansible/roles/biocache-cli/templates/environmentSetupFile.sh

Feel free to reopen this issue if it isn't fixed for you now.
