### ISSUE TITLE
Add robots.txt to ansible scripts

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/ala-install#142]
Robots.txt files can be used to tell automated robots that there is no need to access particular paths. All of the major search engine robots follow robots.txt files, but it isn't a security measure, just prevention of unnecessary traffic.

We should have support for the creation of custom robots.txt files in the ansible scripts. I have manually created some for biocache servers, but a general role/etc. is needed for reuse and automation.

**Comment by ansell** [comment]
@javier-molina This is the issue tracking the automatic addition of robots.txt rules to Apache/nginx configurations. Until this is fixed, it will need to be done manually. Without the robots.txt rules bots hit /ws/ even though they can't do anything with the results and it causes downtime for biocache. We have been able to go down from 3 to 2 virtual machines behind ``biocache.ala.org.au/ws/`` since the robots.txt file was installed, so it is vitally important that it stay in place on any servers that are contacting either solr-b3 or solr-b4 or the solr cloud. 

CC @matthewandrews

**Comment by matthewandrews** [comment]
Happy to do the ansible changes.

**Comment by ansell** [comment]
The relevant Apache configuration on biocache-b3 right now (for reference) is:

```
<Location "/robots.txt">
  SetHandler None
  Require all granted
</Location>
Alias /robots.txt /data/biocache/config/robots.txt
ProxyPass /robots.txt !
```

Michael just manually added robots.txt on profiles.ala.org.au to reduce bot requests there, and the key there was that the ``ProxyPass / ajp...`` had to be last, as it was before the ``ProxyPass /robots.txt`` and was intercepting the request and pushing it to Tomcat instead.

I have never administered an nginx server, so not sure what the equivalents would be there.

**Comment by matthewandrews** [comment]
I've added nginx support for robots.txt now.  A robots.txt response will now always be included in nginx vhosts.  Default is to allow all paths; inventories can specify paths to disallow by setting the `robots_disallow` variable as a list of path strings.  For example:

`robots_disallow=["/ws", "/admin"]`

**Comment by ansell** [comment]
Not worried if this doesn't get fixed in the Apache roles as there is an overall strategy to move to Nginx.
