### ISSUE TITLE
Add nginx support for aliases

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/ala-install#154]
Some servers require nginx aliases, particularly when we are testing new servers.

This is to track possible future automation of this functionality.

**Comment by ansell** [comment]
The server name template is at: https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/nginx_vhost/templates/fragment_20_servername.j2

**Comment by matthewandrews** [comment]
OK support for additional nginx server_name values is now there: add something like this to an inventory to get extra values appended to the primary hostname:

`webserver_extra_servernames=["myalternatehostname.org"]`
or
`webserver_extra_servernames=["myalternatehostname.org", "anothertestdomain.org"]`

**Comment by ansell** [comment]
Thanks, I will open a separate issue for also supporting the server name aliases for tomcat, which involves an extra parameter in the server.xml file
