### ISSUE TITLE
Add loadbalanced_instance variable

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/ala-install#164]
There are some hacks needed to work with the AWS Load Balancer because it doesn't send the Host header with Health Checks. It may be useful to enable these using a new ansible variable so they don't pollute other instances and we can switch the hacks off when AWS realise how useful the HTTP Host header is.

**Comment by matthewandrews** [comment]
This is done now in `nginx_vhost` role: adding `aws_elb_healthcheck_default=true` in an inventory will create a default vhost specifically for AWS ELB health checks.  
There are other options:
`aws_elb_default_port`  (default: 80)
`aws_elb_default_root` (default: /var/www/html)
`aws_elb_default_index` (default: index.html)
You need to manually remove any existing default_server vhost.
