### ISSUE TITLE
Running nginx_vhost with aws load balancer health check enabled conflicts with the preinstalled default host

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/ala-install#175]
Running nginx_vhost role with the aws load balancer health check enabled creates a conflict with the preinstalled nginx default port 80 host:

```
Jun 22 09:32:35 ip-172-30-1-167 nginx[24170]: nginx: [emerg] a duplicate default server for 0.0.0.0:80 in /etc/nginx/sites-enabled/default:17
Jun 22 09:32:35 ip-172-30-1-167 systemd[1]: nginx.service: Control process exited, code=exited status=1
Jun 22 09:32:35 ip-172-30-1-167 systemd[1]: Reload failed for A high performance web server and a reverse proxy server.
```

Can be fixed using ``rm /etc/nginx/sites-enabled/default``

It may also be useful not to have the default host enabled when using nginx_vhost anyway

**Comment by matthewandrews** [comment]
Fixed in 0257441304e293fe4d4414448d1ecfa239e30dec
