### ISSUE TITLE
alerts-vagrant, vars L28 L31(wrong copy/paste?)

### ISSUE THREAD

**Issue by JeGoi** [AtlasOfLivingAustralia/ala-install#176]
var (speciesPages_searchUrl)[https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/inventories/vagrant/alerts-vagrant#L28] and var (collection_searchUrl)[https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/inventories/vagrant/alerts-vagrant#L31] have the same value but different tittles.

**Comment by ansell** [comment]
Thanks, I have fixed the ``speciesPages_searchUrl`` to now point to https://bie.ala.org.au/species/Tiliqua+rugosa as intended
