### ISSUE TITLE
Any experience in using AWX or semaphore in ALA deployments?

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/ala-install#196]
Any experience to configure and schedule jobs to run Ansible playbooks with [awx](https://github.com/ansible/awx) or [semaphore](https://github.com/ansible-semaphore/semaphore) or similar?

I'm trying to find a way to configure & document which playbooks should be run in which hosts, etc.

Any other tip?

Background: I'm using `puppet` in other projects for devops and `ansible` more for puntual commands in all/some hosts (I'm not using playbooks). 

Related question: https://serverfault.com/questions/769636/recurring-ansible-tasks

**Comment by ansell** [comment]
I haven't used either of those. The ALA maintains a private repository with private keys and ALA specific configuration files, but we use the public playbooks here.

We typically run commands directly with the ``ansible-playbook`` CLI, but we should be focusing on improving on that in future.

An partial example of the inventory file we use to setup two of the five servers behind ``biocache.ala.org.au``, those running ``ala-hub``, which is a skinned version of ``biocache-hubs``, and the CLI commands we use is the following, based on ``biocache-hub-standalone.yml`` in this repository as the playbook:

```
# ALA Hub production server installation
# Run with ansible-playbook -i /path/to/ansible-inventories/bhub-b5 /path/to/ala-install/ansible/biocache-hub-standalone.yml --private-key ~/.ssh/id_rsa --user ${USER} --become --ask-become-pass

# playbooks: biocache-hub-standalone

[biocache-hub]
prod-bhub-b5-1.ala.org.au
prod-bhub-b5-2.ala.org.au

[biocache-hub:vars]
is_vagrant=false
#local_repo_dir = ~/.ala
data_dir=/data
tomcat_java_opts = -Xmx8g -Xms8g -Xss256k

biocache_service_url = https://biocache-ws.ala.org.au/ws
biocache_service_base_url = https://biocache-ws.ala.org.au
biocache_service_context_path = /ws

biocache_hub = ala-hub
biocache_hub_version = 3.0.9

biocache_hub_url = https://biocache.ala.org.au
biocache_hub_base_url = https://biocache.ala.org.au
biocache_hub_context_path = 
biocache_hub_hostname = biocache.ala.org.au

collectory_url = https://collections.ala.org.au
collectory_base_url = https://collections.ala.org.au
collectory_context_path =

biocache_hub_uri_filter_pattern=/admin.*,/alaAdmin.*,/download.*
disable_cas = false
bypass_cas = false
auth_base_url = https://auth.ala.org.au
auth_cas_url = https://auth.ala.org.au/cas/login

# Other private information follows so I have only shown part of the file.....
```

**Comment by vjrj** [comment]
Thanks indeed for the info @ansell !
