### ISSUE TITLE
Install the auth-module

### ISSUE THREAD

**Issue by harmandohsa** [AtlasOfLivingAustralia/ala-install#207]
Hello:
I'm getting this error while installing the authentication module of ALA, in my installation of Guatemala (http://snidbgtbio.conap.gob.gt/)
the error rise in this task: 
TASK [mysql : mysql | Install MySQL Packages]
`TASK [mysql : mysql | Install MySQL Packages] **************************************************************************************************************************************************************
failed: [snidbgtbio.conap.gob.gt] (item=[u'mysql-server-5.6', u'mysql-client-5.6', u'python-mysqldb']) => {"cache_update_time": 1540825799, "cache_updated": false, "changed": false, "item": ["mysql-server-5.6", "mysql-client-5.6", "python-mysqldb"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\" 	install 'mysql-server-5.6' 'mysql-client-5.6'' failed: E: Sub-process /usr/bin/dpkg returned an error code (1)\n", "rc": 100, "stderr": "E: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stderr_lines": ["E: Sub-process /usr/bin/dpkg returned an error code (1)"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following package was automatically installed and is no longer required:\n  libevent-core-2.0-5\nUse 'sudo apt autoremove' to remove it.\nThe following additional packages will be installed:\n  libdbd-mysql-perl libdbi-perl libterm-readkey-perl mysql-client-core-5.6\n  mysql-server-core-5.6\nSuggested packages:\n  libclone-perl libmldbm-perl libnet-daemon-perl libsql-statement-perl mailx\n  tinyca\nThe following packages will be REMOVED:\n  mysql-client-5.7 mysql-client-core-5.7 mysql-server-5.7\n  mysql-server-core-5.7\nThe following NEW packages will be installed:\n  libdbd-mysql-perl libdbi-perl libterm-readkey-perl mysql-client-5.6\n  mysql-client-core-5.6 mysql-server-5.6 mysql-server-core-5.6\n0 upgraded, 7 newly installed, 4 to remove and 36 not upgraded.\nNeed to get 20.7 MB of archives.\nAfter this operation, 59.4 kB disk space will be freed.\nGet:1 http://us-central1.gce.archive.ubuntu.com/ubuntu xenial/main amd64 libdbi-perl amd64 1.634-1build1 [743 kB]\nGet:2 http://us-central1.gce.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 libdbd-mysql-perl amd64 4.033-1ubuntu0.1 [84.3 kB]\nGet:3 http://us-central1.gce.archive.ubuntu.com/ubuntu xenial/universe amd64 libterm-readkey-perl amd64 2.33-1build1 [27.2 kB]\nGet:4 http://archive.ubuntu.com/ubuntu trusty/universe amd64 mysql-client-core-5.6 amd64 5.6.16-1~exp1 [4084 kB]\nGet:5 http://archive.ubuntu.com/ubuntu trusty/universe amd64 mysql-client-5.6 amd64 5.6.16-1~exp1 [5591 kB]\nGet:6 http://archive.ubuntu.com/ubuntu trusty/universe amd64 mysql-server-core-5.6 amd64 5.6.16-1~exp1 [4333 kB]\nGet:7 http://archive.ubuntu.com/ubuntu trusty/universe amd64 mysql-server-5.6 amd64 5.6.16-1~exp1 [5839 kB]\nPreconfiguring packages ...\nFetched 20.7 MB in 12s (1678 kB/s)\n(Reading database ... \r(Reading database ... 5%\r(Reading database ... 10%\r(Reading database ... 15%\r(Reading database ... 20%\r(Reading database ... 25%\r(Reading database ... 30%\r(Reading database ... 35%\r(Reading database ... 40%\r(Reading database ... 45%\r(Reading database ... 50%\r(Reading database ... 55%\r(Reading database ... 60%\r(Reading database ... 65%\r(Reading database ... 70%\r(Reading database ... 75%\r(Reading database ... 80%\r(Reading database ... 85%\r(Reading database ... 90%\r(Reading database ... 95%\r(Reading database ... 100%\r(Reading database ... 111717 files and directories currently installed.)\r\nRemoving mysql-server-5.7 (5.7.24-0ubuntu0.16.04.1) ...\r\nupdate-alternatives: using /etc/mysql/my.cnf.fallback to provide /etc/mysql/my.cnf (my.cnf) in auto mode\r\nRemoving mysql-client-5.7 (5.7.24-0ubuntu0.16.04.1) ...\r\nRemoving mysql-client-core-5.7 (5.7.24-0ubuntu0.16.04.1) ...\r\nRemoving mysql-server-core-5.7 (5.7.24-0ubuntu0.16.04.1) ...\r\nProcessing triggers for man-db (2.7.5-1) ...\r\nSelecting previously unselected package libdbi-perl.\r\n(Reading database ... \r(Reading database ... 5%\r(Reading database ... 10%\r(Reading database ... 15%\r(Reading database ... 20%\r(Reading database ... 25%\r(Reading database ... 30%\r(Reading database ... 35%\r(Reading database ... 40%\r(Reading database ... 45%\r(Reading database ... 50%\r(Reading database ... 55%\r(Reading database ... 60%\r(Reading database ... 65%\r(Reading database ... 70%\r(Reading database ... 75%\r(Reading database ... 80%\r(Reading database ... 85%\r(Reading database ... 90%\r(Reading database ... 95%\r(Reading database ... 100%\r(Reading database ... 111501 files and directories currently installed.)\r\nPreparing to unpack .../libdbi-perl_1.634-1build1_amd64.deb ...\r\nUnpacking libdbi-perl (1.634-1build1) ...\r\nSelecting previously unselected package libdbd-mysql-perl.\r\nPreparing to unpack .../libdbd-mysql-perl_4.033-1ubuntu0.1_amd64.deb ...\r\nUnpacking libdbd-mysql-perl (4.033-1ubuntu0.1) ...\r\nSelecting previously unselected package libterm-readkey-perl.\r\nPreparing to unpack .../libterm-readkey-perl_2.33-1build1_amd64.deb ...\r\nUnpacking libterm-readkey-perl (2.33-1build1) ...\r\nSelecting previously unselected package mysql-client-core-5.6.\r\nPreparing to unpack .../mysql-client-core-5.6_5.6.16-1~exp1_amd64.deb ...\r\nUnpacking mysql-client-core-5.6 (5.6.16-1~exp1) ...\r\nSelecting previously unselected package mysql-client-5.6.\r\nPreparing to unpack .../mysql-client-5.6_5.6.16-1~exp1_amd64.deb ...\r\nUnpacking mysql-client-5.6 (5.6.16-1~exp1) ...\r\nSelecting previously unselected package mysql-server-core-5.6.\r\nPreparing to unpack .../mysql-server-core-5.6_5.6.16-1~exp1_amd64.deb ...\r\nUnpacking mysql-server-core-5.6 (5.6.16-1~exp1) ...\r\nSelecting previously unselected package mysql-server-5.6.\r\nPreparing to unpack .../mysql-server-5.6_5.6.16-1~exp1_amd64.deb ...\r\nAborting downgrade from (at least) 5.7 to 5.6.\r\nIf are sure you want to downgrade to 5.6, remove the file\r\n/var/lib/mysql/debian-*.flag and try installing again.\r\ndpkg: error processing archive /var/cache/apt/archives/mysql-server-5.6_5.6.16-1~exp1_amd64.deb (--unpack):\r\n subprocess new pre-installation script returned error exit status 1\r\nProcessing triggers for man-db (2.7.5-1) ...\r\nErrors were encountered while processing:\r\n /var/cache/apt/archives/mysql-server-5.6_5.6.16-1~exp1_amd64.deb\r\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following package was automatically installed and is no longer required:", "  libevent-core-2.0-5", "Use 'sudo apt autoremove' to remove it.", "The following additional packages will be installed:", "  libdbd-mysql-perl libdbi-perl libterm-readkey-perl mysql-client-core-5.6", "  mysql-server-core-5.6", "Suggested packages:", "  libclone-perl libmldbm-perl libnet-daemon-perl libsql-statement-perl mailx", "  tinyca", "The following packages will be REMOVED:", "  mysql-client-5.7 mysql-client-core-5.7 mysql-server-5.7", "  mysql-server-core-5.7", "The following NEW packages will be installed:", "  libdbd-mysql-perl libdbi-perl libterm-readkey-perl mysql-client-5.6", "  mysql-client-core-5.6 mysql-server-5.6 mysql-server-core-5.6", "0 upgraded, 7 newly installed, 4 to remove and 36 not upgraded.", "Need to get 20.7 MB of archives.", "After this operation, 59.4 kB disk space will be freed.", "Get:1 http://us-central1.gce.archive.ubuntu.com/ubuntu xenial/main amd64 libdbi-perl amd64 1.634-1build1 [743 kB]", "Get:2 http://us-central1.gce.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 libdbd-mysql-perl amd64 4.033-1ubuntu0.1 [84.3 kB]", "Get:3 http://us-central1.gce.archive.ubuntu.com/ubuntu xenial/universe amd64 libterm-readkey-perl amd64 2.33-1build1 [27.2 kB]", "Get:4 http://archive.ubuntu.com/ubuntu trusty/universe amd64 mysql-client-core-5.6 amd64 5.6.16-1~exp1 [4084 kB]", "Get:5 http://archive.ubuntu.com/ubuntu trusty/universe amd64 mysql-client-5.6 amd64 5.6.16-1~exp1 [5591 kB]", "Get:6 http://archive.ubuntu.com/ubuntu trusty/universe amd64 mysql-server-core-5.6 amd64 5.6.16-1~exp1 [4333 kB]", "Get:7 http://archive.ubuntu.com/ubuntu trusty/universe amd64 mysql-server-5.6 amd64 5.6.16-1~exp1 [5839 kB]", "Preconfiguring packages ...", "Fetched 20.7 MB in 12s (1678 kB/s)", "(Reading database ... ", "(Reading database ... 5%", "(Reading database ... 10%", "(Reading database ... 15%", "(Reading database ... 20%", "(Reading database ... 25%", "(Reading database ... 30%", "(Reading database ... 35%", "(Reading database ... 40%", "(Reading database ... 45%", "(Reading database ... 50%", "(Reading database ... 55%", "(Reading database ... 60%", "(Reading database ... 65%", "(Reading database ... 70%", "(Reading database ... 75%", "(Reading database ... 80%", "(Reading database ... 85%", "(Reading database ... 90%", "(Reading database ... 95%", "(Reading database ... 100%", "(Reading database ... 111717 files and directories currently installed.)", "Removing mysql-server-5.7 (5.7.24-0ubuntu0.16.04.1) ...", "update-alternatives: using /etc/mysql/my.cnf.fallback to provide /etc/mysql/my.cnf (my.cnf) in auto mode", "Removing mysql-client-5.7 (5.7.24-0ubuntu0.16.04.1) ...", "Removing mysql-client-core-5.7 (5.7.24-0ubuntu0.16.04.1) ...", "Removing mysql-server-core-5.7 (5.7.24-0ubuntu0.16.04.1) ...", "Processing triggers for man-db (2.7.5-1) ...", "Selecting previously unselected package libdbi-perl.", "(Reading database ... ", "(Reading database ... 5%", "(Reading database ... 10%", "(Reading database ... 15%", "(Reading database ... 20%", "(Reading database ... 25%", "(Reading database ... 30%", "(Reading database ... 35%", "(Reading database ... 40%", "(Reading database ... 45%", "(Reading database ... 50%", "(Reading database ... 55%", "(Reading database ... 60%", "(Reading database ... 65%", "(Reading database ... 70%", "(Reading database ... 75%", "(Reading database ... 80%", "(Reading database ... 85%", "(Reading database ... 90%", "(Reading database ... 95%", "(Reading database ... 100%", "(Reading database ... 111501 files and directories currently installed.)", "Preparing to unpack .../libdbi-perl_1.634-1build1_amd64.deb ...", "Unpacking libdbi-perl (1.634-1build1) ...", "Selecting previously unselected package libdbd-mysql-perl.", "Preparing to unpack .../libdbd-mysql-perl_4.033-1ubuntu0.1_amd64.deb ...", "Unpacking libdbd-mysql-perl (4.033-1ubuntu0.1) ...", "Selecting previously unselected package libterm-readkey-perl.", "Preparing to unpack .../libterm-readkey-perl_2.33-1build1_amd64.deb ...", "Unpacking libterm-readkey-perl (2.33-1build1) ...", "Selecting previously unselected package mysql-client-core-5.6.", "Preparing to unpack .../mysql-client-core-5.6_5.6.16-1~exp1_amd64.deb ...", "Unpacking mysql-client-core-5.6 (5.6.16-1~exp1) ...", "Selecting previously unselected package mysql-client-5.6.", "Preparing to unpack .../mysql-client-5.6_5.6.16-1~exp1_amd64.deb ...", "Unpacking mysql-client-5.6 (5.6.16-1~exp1) ...", "Selecting previously unselected package mysql-server-core-5.6.", "Preparing to unpack .../mysql-server-core-5.6_5.6.16-1~exp1_amd64.deb ...", "Unpacking mysql-server-core-5.6 (5.6.16-1~exp1) ...", "Selecting previously unselected package mysql-server-5.6.", "Preparing to unpack .../mysql-server-5.6_5.6.16-1~exp1_amd64.deb ...", "Aborting downgrade from (at least) 5.7 to 5.6.", "If are sure you want to downgrade to 5.6, remove the file", "/var/lib/mysql/debian-*.flag and try installing again.", "dpkg: error processing archive /var/cache/apt/archives/mysql-server-5.6_5.6.16-1~exp1_amd64.deb (--unpack):", " subprocess new pre-installation script returned error exit status 1", "Processing triggers for man-db (2.7.5-1) ...", "Errors were encountered while processing:", " /var/cache/apt/archives/mysql-server-5.6_5.6.16-1~exp1_amd64.deb"]}`

**Comment by harmandohsa** [comment]
Hi
i'm runnin this playbook:  ansible-playbook --private-key ~/.ssh/google_compute_engine -u -s jorge.garcia.conap -i inventories/vagrant/auth-snidbgt.conap.gob.gt auth-standalone.yml

i installed the DEMO with this playbook: ansible-playbook --private-key /tmp/google_compute_engine/google_compute_engine.ppk -u root -i inventories/snidbgt.conap.gob.gt ala-demo.yml

my version of ubuntu is: Ubuntu 16.04.5

**Comment by ansell** [comment]
There are references to Ubuntu Trusty, which is 14.04, in the error message, so there may be some complication in ansible where it is installing to a different server to what you expect.

@sbearcsiro Which playbook should be used to install a new instance of auth? Should ``auth-standalone.yml`` and ``cas-standalone.yml`` be deleted at this point if they are redundant to ``aws-cas-5.yml``?

**Comment by matthewandrews** [comment]
`auth-standalone.yml` is specifying `mysql` role (which is currently installing mysql 5.6) whereas the rest of ala-demo is using the `mysql-5.7` role.  

`cas-standalone` should probably be deleted; if we're going to keep on supporting cas 2, we could update `auth-standalone.yml` to use` mysql-5.7` role.

**Comment by harmandohsa** [comment]
After changin the role mySql to MySql-5.7 the previus error is gone, but i have a new error this:
TASK [userdetails : copy userdetails-config.yml] ***********************************************************************************************************************************************************
fatal: [snidbgtbio.conap.gob.gt]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'cas_server_name' is undefined"}

here a copy of my inventory file, i dont if i'm missing something
`[auth]
snidbgtbio.conap.gob.gt

[auth:vars]
is_vagrant=true
local_repo_dir=~/.ala
data_dir=/data

cas_hostname=snidbgtbio.conap.gob.gt
cas_url=https://snidbgtbio.conap.gob.gt/cas
cas_base_url=https://snidbgtbio.conap.gob.gt
cas_context_path=/cas

userdetails_hostname=snidbgtbio.conap.gob.gt
userdetails_url=https://snidbgtbio.conap.gob.gt/userdetails
userdetails_base_url=https://snidbgtbio.conap.gob.gt
userdetails_context_path=/userdetails

ticket_registry_db_name=casTicketRegistry
ticket_registry_db_hostname=localhost
ticket_registry_db_username=ticket
ticket_registry_db_password=ticket

user_store_db_name=emmet
user_store_db_hostname=localhost
user_store_db_username=userstore
user_store_db_password=userstore

apikey_hostname=auth.snidbgtbio.conap.gob.gt
apikey_context_path=/apikey
apikey_base_url=http://auth.snidbgtbio.conap.gob.gt
apikey_url=http://auth.snidbgtbio.conap.gob.gt/apikey

apikey_db_name=apikey
apikey_db_username=apikey
apikey_db_password=apikey
apikey_db_hostname=localhost

oauth_providers_flickr_key=somekey
oauth_providers_flickr_secret=somesecret

user_store_db_encoding_salt=salt
user_store_db_encoding_algorithm=MD5

auth_base_url=https://auth.snidbgtbio.conap.gob.gt
auth_cas_url=https://snidbgtbio.conap.gob.gt/cas

sightings_base_url=https://sightings.snidbgtbio.conap.gob.gt
spatial_base_url=https://spatial.snidbgtbio.conap.gob.gt
volunteer_base_url=https://volunteer.snidbgtbio.conap.gob.gt
lists_base_url=https://lists.snidbgtbio.conap.gob.gt
biocache_base_url=https://biocache.snidbgtbio.conap.gob.gt
alerts_base_url=https://alerts.snidbgtbio.conap.gob.gt

pac4j_callback_url=https://snidbgtbio.conap.gob.gt/cas/login

#facebook
pac4j_facebook_consumer_key=to_be_added
pac4j_facebook_consumer_secret=to_be_added

# twitter
pac4j_twitter_consumer_key=to_be_added
pac4j_twitter_consumer_secret=to_be_added

# github
pac4j_github_consumer_key=to_be_added
pac4j_github_consumer_secret=to_be_added

# google
pac4j_google_consumer_key=to_be_added
pac4j_google_consumer_secret=to_be_added

# linkedin
pac4j_linkedin_consumer_key=to_be_added
pac4j_linkedin_consumer_secret=to_be_added

# windows live
pac4j_windows_consumer_key=to_be_added
pac4j_windows_consumer_secret=to_be_added

# yahoo OAuth and OpenID
pac4j_yahoo_consumer_key=to_be_added--
pac4j_yahoo_consumer_secret=to_be_added

# automatic registration ALA user password
user_create_password=to_be_added

#
# SSL Configuration files
#
ssl=true
copy_https_certs_from_local=true
force_https=true
ssl_certificate_server_dir=/etc/apache2
ssl_certificate_local_dir=/home/hector/Descargas/sslforfree
ssl_cert_file=certificate.crt
ssl_key_file=private.key
ssl_chain_file=ca_bundle.crt

oauth_providers_flickr_callback=
oauth_providers_flickr_secret=
oauth_providers_flickr_callback=

api_key=
`

**Comment by harmandohsa** [comment]
Well, my site stop running after the installation of the playbook auth-standalone.yml, 
you can see the error here: https://snidbgtbio.conap.gob.gt/collectory/
basicly is in all site, https://snidbgtbio.conap.gob.gt/
I can see the index, but everything else is down

What can i do?

**Comment by djtfmartin** [comment]
thanks @harmandohsa 
I am guessing tomcat is down. Have you tried restarting ?

```
sudo service tomcat7 restart
```

Probably best to discuss getting your server back up on Slack.

One thing we should have said, is that it is recommend that the auth module is installed on a separate virtual machine.

**Comment by harmandohsa** [comment]
thanks @djtfmartin  
yes i have restarting tomcat, mysql and apache, but still getting the same error

**Comment by djtfmartin** [comment]
i would check the logs /var/log/tomcat7 on the server for more information. Im not sure what happened on the server. Running that ansible script should not of removed any existing applications.

**Comment by djtfmartin** [comment]
Yes, possibly. Would be useful to know why its not running though.

**Comment by harmandohsa** [comment]
there are several files in this route /var/log/tomcat7, wich one should i check?
`ala-bie.log            biocache-service.log                       catalina.2018-10-17.log.gz  catalina.2018-10-30.log      localhost.2018-10-19.log.gz          localhost_access_log.2018-10-19.txt  logger.log
ala-bie.log.gz         biocache-service.log.2018-10-18T00:25:56Z  catalina.2018-10-18.log.gz  catalina.out                 localhost.2018-10-21.log.gz          localhost_access_log.2018-10-21.txt  logger.log.gz
ala-collectory.log     cas.log                                    catalina.2018-10-19.log.gz  catalina.out.1.gz            localhost.2018-10-23.log.gz          localhost_access_log.2018-10-23.txt  perfStats.log
ala-collectory.log.gz  cas.log.2018-10-30T04:26:44Z               catalina.2018-10-21.log.gz  catalina.out.2.gz            localhost.2018-10-26.log.gz          localhost_access_log.2018-10-26.txt  specieslist-webapp.log
ala-hub.log            cas.log.2018-10-30T04:40:51Z               catalina.2018-10-23.log.gz  images.log                   localhost.2018-10-29.log.gz          localhost_access_log.2018-10-27.txt  specieslist-webapp.log.gz
ala-hub.log.gz         cas.log.2018-10-30T05:02:23Z               catalina.2018-10-26.log.gz  images.log.gz                localhost.2018-10-30.log             localhost_access_log.2018-10-28.txt
bie-index.log          cas.log.2018-10-30T05:23:41Z               catalina.2018-10-27.log.gz  localhost.2018-10-17.log.gz  localhost_access_log.2018-10-17.txt  localhost_access_log.2018-10-29.txt
bie-index.log.gz       cas.log.2018-10-30T05:45:03Z               catalina.2018-10-29.log.gz  localhost.2018-10-18.log.gz  localhost_access_log.2018-10-18.txt  localhost_access_log.2018-10-30.txt`

**Comment by harmandohsa** [comment]
Hi @djtfmartin dont know if this file have the issue, i see some 404

`127.0.0.1 - - [29/Oct/2018:18:11:40 +0000] "GET /specieslists/ws/speciesList/?isThreatened=eq:true&isAuthoritative=eq:true HTTP/1.1" 404 -
127.0.0.1 - - [29/Oct/2018:18:11:40 +0000] "GET /specieslists/ws/speciesList/?isThreatened=eq:true&isAuthoritative=eq:true HTTP/1.1" 404 -
200.119.134.140 - - [29/Oct/2018:18:13:25 +0000] "GET /collectory/ HTTP/1.1" 404 -
200.119.134.140 - - [29/Oct/2018:18:15:08 +0000] "GET /collectory/datasets HTTP/1.1" 404 -
200.119.134.140 - - [29/Oct/2018:18:16:44 +0000] "GET /collectory/ HTTP/1.1" 404 -
200.119.134.140 - - [29/Oct/2018:18:16:50 +0000] "GET /collectory/admin HTTP/1.1" 404 -
200.119.134.140 - - [29/Oct/2018:18:16:57 +0000] "GET /collectory/admin HTTP/1.1" 404 -
34.226.200.251 - - [29/Oct/2018:18:17:43 +0000] "GET /collectory/admin HTTP/1.1" 404 -
107.23.128.48 - - [29/Oct/2018:18:17:43 +0000] "GET /collectory/admin HTTP/1.1" 404 -
200.119.134.140 - - [29/Oct/2018:18:18:51 +0000] "GET /collectory/ HTTP/1.1" 404 -
54.152.0.39 - - [29/Oct/2018:18:19:05 +0000] "GET /collectory/ HTTP/1.1" 404 -
34.226.200.251 - - [29/Oct/2018:18:19:05 +0000] "GET /collectory/ HTTP/1.1" 404 -
200.119.134.140 - - [29/Oct/2018:18:19:37 +0000] "GET /collectory/datasets HTTP/1.1" 404 -
52.72.111.29 - - [29/Oct/2018:18:19:56 +0000] "GET /collectory/datasets HTTP/1.1" 404 -
34.239.107.223 - - [29/Oct/2018:18:19:56 +0000] "GET /collectory/datasets HTTP/1.1" 404 -
66.249.75.149 - - [29/Oct/2018:18:22:19 +0000] "GET /logger-service/admin/userReport/download?fileName=user-report-dr7.csv&entityUids=dr7&eventId=1002 HTTP/1.1" 404 -
66.249.75.147 - - [29/Oct/2018:18:22:20 +0000] "GET /collectory/dataResource/edit/dr2?page=contribution HTTP/1.1" 404 -
200.119.134.140 - - [29/Oct/2018:18:36:23 +0000] "GET /collectory/ HTTP/1.1" 404 -
66.249.75.145 - - [29/Oct/2018:18:52:37 +0000] "GET /collectory/dataResource/editConsumers/dr7?source=co HTTP/1.1" 404 -
66.249.75.145 - - [29/Oct/2018:18:57:40 +0000] "GET /collectory/dataResource/edit/dr7?page=%2Fshared%2Fbase&notAuthorisedMessage=You+are+not+authorised+to+edit+this+resource. HTTP/1.1" 404 -
66.249.75.149 - - [29/Oct/2018:19:02:25 +0000] "GET /collectory/licence/show/14 HTTP/1.1" 404 -
66.249.75.145 - - [29/Oct/2018:19:07:46 +0000] "GET /specieslists/speciesList/list?sort=ownerFullName&order=desc&max=50 HTTP/1.1" 404 -
66.249.88.49 - - [29/Oct/2018:19:08:56 +0000] "GET /collectory/admin HTTP/1.1" 404 -
66.249.75.147 - - [29/Oct/2018:19:12:29 +0000] "GET /collectory/licence/show/8 HTTP/1.1" 404 -
66.249.75.145 - - [29/Oct/2018:19:12:49 +0000] "GET /collectory/dataResource/edit/dr7?page=%2FdataResource%2FimageMetadata HTTP/1.1" 404 -
66.249.75.145 - - [29/Oct/2018:19:17:52 +0000] "GET /collectory/dataResource/edit/dr7?page=description HTTP/1.1" 404 -
66.249.75.147 - - [29/Oct/2018:19:22:26 +0000] "GET /collectory/licence/show/17 HTTP/1.1" 404 -
66.249.75.145 - - [29/Oct/2018:19:22:55 +0000] "GET /logger-service/admin/userReport/downloadDetailed?fileName=user-report-detailed-dr7.csv&entityUids=dr7&eventId=1002 HTTP/1.1" 404 -
66.249.75.145 - - [29/Oct/2018:19:43:07 +0000] "GET /specieslists/speciesList/list?sort=ownerFullName&order=desc&max=10 HTTP/1.1" 404 -
66.249.75.145 - - [29/Oct/2018:19:48:10 +0000] "GET /collectory/dataResource/edit/dr7?page=%2Fshared%2FshowContacts HTTP/1.1" 404 -
127.0.0.1 - - [29/Oct/2018:19:58:19 +0000] "GET /collectory/ws/dataResource/dr4 HTTP/1.1" 404 -
66.249.75.145 - - [29/Oct/2018:20:02:17 +0000] "GET /collectory/licence/show/18 HTTP/1.1" 404 -
127.0.0.1 - - [29/Oct/2018:20:08:22 +0000] "GET /collectory/ws/dataResource/dr4 HTTP/1.1" 404 -
66.249.75.145 - - [29/Oct/2018:20:33:37 +0000] "GET /specieslists/speciesList/fieldGuide/drt1540327381184?fq=&max=25&sort=itemOrder&order=&offset=0&q=&id=drt1540327381184&controller=speciesListItem&action=list&fetch=%7BkvpValues%3Dselect%7D HTTP/
1.1" 404 -
66.249.75.145 - - [29/Oct/2018:20:42:08 +0000] "GET /collectory/licence/show/5 HTTP/1.1" 404 -
66.249.75.145 - - [29/Oct/2018:20:43:43 +0000] "GET /logger-service/admin/userReport/downloadDetailed?fileName=user-report-detailed-dp0.csv&entityUids=dr7&eventId=1002 HTTP/1.1" 404 -
66.249.75.147 - - [29/Oct/2018:21:03:55 +0000] "GET /logger-service/admin/userReport/download?fileName=user-report-dp0.csv&entityUids=dr7&eventId=1002 HTTP/1.1" 404 -
66.249.75.147 - - [29/Oct/2018:21:08:58 +0000] "GET /specieslists/speciesList/fieldGuide/drt1540327381184?fq=&max=50&sort=itemOrder&order=&offset=0&q=&id=drt1540327381184&controller=speciesListItem&action=list&fetch=%7BkvpValues%3Dselect%7D HTTP/
1.1" 404 -
127.0.0.1 - - [29/Oct/2018:21:12:23 +0000] "GET /collectory/ws/dataResource/dr4 HTTP/1.1" 404 -
200.119.134.140 - - [29/Oct/2018:21:12:59 +0000] "GET /collectory/ HTTP/1.1" 404 -
200.119.134.140 - - [29/Oct/2018:21:18:55 +0000] "GET /specieslists/public/speciesLists HTTP/1.1" 404 -
200.119.134.140 - - [29/Oct/2018:21:19:03 +0000] "GET /collectory/datasets HTTP/1.1" 404 -
66.249.75.147 - - [29/Oct/2018:21:19:04 +0000] "GET /specieslists/speciesList/spatialPortal/drt1540327381184?fq=&max=25&sort=itemOrder&order=&offset=0&q=&id=drt1540327381184&controller=speciesListItem&action=list&fetch=%7BkvpValues%3Dselect%7D&ty
pe=Search HTTP/1.1" 404 -
200.119.134.140 - - [29/Oct/2018:21:19:08 +0000] "GET /collectory/admin HTTP/1.1" 404 -
66.249.75.149 - - [29/Oct/2018:21:24:07 +0000] "GET /specieslists/speciesListItem/downloadList/drt1540327381184?fq=&max=50&sort=itemOrder&order=&offset=0&q=&id=drt1540327381184&controller=speciesListItem&action=list&fetch=%7BkvpValues%3Dselect%7D
&file= HTTP/1.1" 404 -
66.249.75.147 - - [29/Oct/2018:21:29:10 +0000] "GET /specieslists/speciesList/occurrences/drt1540327381184?fq=&max=25&sort=itemOrder&order=&offset=0&q=&id=drt1540327381184&controller=speciesListItem&action=list&fetch=%7BkvpValues%3Dselect%7D&type
=Search HTTP/1.1" 404 -
66.249.75.145 - - [29/Oct/2018:21:49:22 +0000] "GET /specieslists/speciesList/occurrences/drt1540327381184?fq=&max=25&sort=itemOrder&order=&offset=0&q=&id=drt1540327381184&controller=speciesListItem&action=list&fetch=%7BkvpValues%3Dselect%7D&type
=Download&email= HTTP/1.1" 404 -
66.249.75.149 - - [29/Oct/2018:21:52:27 +0000] "GET /collectory/licence/show/3 HTTP/1.1" 404 -
66.249.75.145 - - [29/Oct/2018:21:54:25 +0000] "GET /specieslists/speciesList/spatialPortal/drt1540327381184?fq=&max=50&sort=itemOrder&order=&offset=0&q=&id=drt1540327381184&controller=speciesListItem&action=list&fetch=%7BkvpValues%3Dselect%7D&ty
pe=Search HTTP/1.1" 404 -
66.249.75.145 - - [29/Oct/2018:21:59:28 +0000] "GET /specieslists/speciesList/occurrences/drt1540327381184?fq=&max=50&sort=itemOrder&order=&offset=0&q=&id=drt1540327381184&controller=speciesListItem&action=list&fetch=%7BkvpValues%3Dselect%7D&type
=Download&email= HTTP/1.1" 404 -
200.119.134.140 - - [29/Oct/2018:22:03:31 +0000] "GET /collectory/ HTTP/1.1" 404 -
52.71.192.87 - - [29/Oct/2018:22:03:55 +0000] "GET /collectory/ HTTP/1.1" 404 -
54.234.37.47 - - [29/Oct/2018:22:03:56 +0000] "GET /collectory/ HTTP/1.1" 404 -
66.249.75.145 - - [29/Oct/2018:22:04:31 +0000] "GET /specieslists/speciesListItem/downloadList/drt1540327381184?fq=&max=25&sort=itemOrder&order=&offset=0&q=&id=drt1540327381184&controller=speciesListItem&action=list&fetch=%7BkvpValues%3Dselect%7D
&file= HTTP/1.1" 404 -
"localhost_access_log.2018-10-29.txt" [readonly] 118L, 13624C                                                                                                                                                                       1,1           Top
`

**Comment by harmandohsa** [comment]
Well after several test, my portal dont work again like it was before of installation of auth-standalone.yml
I restores a snapshot that i was take before that installation.

Thanks guys
