### ISSUE TITLE
java.lang.NoClassDefFoundError: com/sun/javafx/iio/ImageMetadata

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/ala-install#236]
Our images ingestion where falling after upgrading our images service (to latest version) with this error:
`java.lang.NoClassDefFoundError: com/sun/javafx/iio/ImageMetadata` 
as now we are also using `openjdk` by default:
```
root@gbif18-images:/var/log/tomcat7# java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```
We fixed it installing `openjfx`. I'll do a small PR for this.

**Comment by djtfmartin** [comment]
thanks @vrjr
