### ISSUE TITLE
404 in nexus trying to download species-list 

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/ala-install#244]
Hi, I get a 404 running the demo playbook in specieslist role:
https://nexus.ala.org.au/service/local/artifact/maven/redirect?r=public&g=au.org.ala&a=specieslist-webapp&v=LATEST&e=jar&c=exec

I've tried setting `species_list_version` to other different that LATEST with same 404 error.

TIA,

**Comment by djtfmartin** [comment]
thanks @vjrj which playbook are you testing with ?

I just tested with 

```
ansible-playbook --private-key ~/.vagrant.d/insecure_private_key -vvvv -u vagrant -s -i ala-install/ansible/inventories/vagrant/species-list-vagrant ala-install/ansible/species-list-standalone.yml
```
and seems ok.

**Comment by vjrj** [comment]
I'm using: 
https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/ala-demo.yml
Thanks @djtfmartin

**Comment by djtfmartin** [comment]
ill test locally

i did noticed that the species-lists/vars/main.yml wasnt specifying packaging like so
```
packaging: "war"
```

**Comment by djtfmartin** [comment]
I couldnt reproduce. I will add the 

```
packaging: "war"
```

anyway to be explicit

**Comment by vjrj** [comment]
Sorry @djtfmartin, it's my fault. 

I added CAS to our demo inventory some days ago just to test and didn't realize this side effect (I only run some tags like 'cas' etc).

https://demo.gbif.es/cas

Commenting our new roles (cas, userdetails, etc) fix this, so I'll try to debug. 

So sorry to wasting your time...

**Comment by djtfmartin** [comment]
no no - all good :)

thanks @vjrj

**Comment by vjrj** [comment]
@djtfmartin, I had finally the time to debug this, and adding `classifiers` and `packaging` to image and specieslist var roles as you pointed fix this for my demo fork. I'll send a PR so others don't suffer this 404 if they mix these services/roles in the same inventory.

```
diff --git a/ansible/roles/image-service/vars/main.yml b/ansible/roles/image-service/vars/main.yml
index ff813d43..f5e25ef6 100644
--- a/ansible/roles/image-service/vars/main.yml
+++ b/ansible/roles/image-service/vars/main.yml
@@ -3,6 +3,8 @@ version: "{{ images_version | default('LATEST') }}"
 artifactId: "ala-images"
 groupId: "au.org.ala"
 images_url: "{{maven_repo_ws_url}}"
+classifier: ""
+packaging: "war"
 
 additional_proxy_pass:
   - { src: "/store", dest: "!" }
\ No newline at end of file
diff --git a/ansible/roles/species-list/vars/main.yml b/ansible/roles/species-list/vars/main.yml
index 52582a42..916702e8 100644
--- a/ansible/roles/species-list/vars/main.yml
+++ b/ansible/roles/species-list/vars/main.yml
@@ -3,3 +3,5 @@ version: "{{ species_list_version | default('LATEST') }}"
 artifactId: "specieslist-webapp"
 groupId: "au.org.ala"
 specieslist_war_url: "{{maven_repo_ws_url}}"
+classifier: ""
+packaging: "war"
```
