### ISSUE TITLE
CDN links are broken

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/ala-install#25]
Current installs with use_cdn_repos=true are broken due to changes in the construction of the URLs.

Suggest constructing a direct directory path instead of a webservice call when use_cdn_repos=true.
This might necessitate an additional 'directory' variable to use instead of package.

See https://github.com/AtlasOfLivingAustralia/ala-install/commit/130a2939e71cb0bc833a676f22f7268b3bd824f6

**Comment by aruizca** [comment]
Please pull the changes and check that it is working for you too.

**Comment by djtfmartin** [comment]
closing
