### ISSUE TITLE
Upgrade ansible supported version to 2.8

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/ala-install#298]
Ansible 2.8 has been released. We should test on ci that it has no new regressions past those already existing on ci and organise an update date for updating developers to use it.

Regressions:

- [x] Regression in `nginx_vhost` during handler logic: ```TASK [nginx_vhost : ensure nginx cache dir is present if configured] ***********
ok: [test-xyz.ala.org.au] TASK [nginx_vhost : ensure nginx cache dir will be cleared by handler] *********
ERROR! The requested handler 'clear nginx cache' was not found in either the main handlers list nor in the listening handlers list```
- [x] Regression in `image-service` with notify logic: ```ERROR! 'notify' is not a valid attribute for a IncludeRole The error appears to be in '/Users/ans025/gitrepos/ala-install/ansible/roles/image-service/tasks/main.yml': line 28, column 3, but may be elsewhere in the file depending on the exact syntax problem. The offending line appears to be: - name: add nginx vhost if configured
  ^ here``` Fixed by removing the notify statement. If the notify is needed, it would be triggered from one of the tasks in the `nginx_vhost` role when necessary.
- [x] Regression in `postgresql` role with undefined variable where the check logic changed: ```TASK [postgresql : install setfacl support] 
- [ ] When using Apache with ssl without `ssl_chain_filepath` defined, the role tries to configure with "True" as default value [here](https://github.com/AtlasOfLivingAustralia/ala-install/blob/3d4cdf00d1bae71e1ba3c9c59004c9c2538370f5/ansible/library/apache_vhost#L202).
- [ ] In demo/workshop playbooks, `postgis_version` is interpreted as float. See [PR](https://github.com/AtlasOfLivingAustralia/ala-install/pull/305)
*********************************************************************************************************************************************************
task path: /Users/ans025/gitrepos/ala-install/ansible/roles/postgresql/tasks/postgis.yml:1
fatal: [nci-image-service.ala.org.au]: FAILED! => {
    "msg": "The conditional check 'postgis_version' failed. The error was: error while evaluating conditional (postgis_version): 'postgis_version' is undefined\n\nThe error appears to be in '/Users/ans025/gitrepos/ala-install/ansible/roles/postgresql/tasks/postgis.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: install setfacl support\n  ^ here\n"``` Fixed by correcting the test to use `postgis_version is defined and postgis_version | length > 0` so it explicitly checks for existence and non-emptiness

Deprecation warnings:

- [ ] Deprecation warning: Replace any dash character in group names `-` with `_`. Group names are internally transformed into python class instances so group names should be valid python identifiers, which they are not currently for cases where we use a dash character. This is a deprecation warning for ansible-2.10) The relevant error message is ```[DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad characters in group names by default, this will change, but still be user configurable on deprecation. 
This feature will be removed in version 2.10. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details```
- [x] Deprecation warning: boolean variables that are not being piped through `|bool` currently when ini inventories are used: ```TASK [nginx_vhost : ensure sites-available dir is present] *********************
[DEPRECATION WARNING]: evaluating vhost_required as a bare variable, this 
behaviour will go away and you might need to add |bool to the expression in the
 future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This feature 
will be removed in version 2.12. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.```

Final steps
- [ ] Advertise the date for the swapover a week in advance
- [ ] Changeover the supported version variable
- [ ] Update the README

**Comment by vjrj** [comment]
A minor comment: The README should be updated in some point.

**Comment by ansell** [comment]
Thanks, I have added three extra tasks for what needs to be done once testing has completed and the bugs have been fixed.

**Comment by ansell** [comment]
@djtfmartin Please don't remove `| bool == True` references. Asking for review before merging Pull Requests with extra changes is also recommended to avoid these issues in future.

**Comment by ansell** [comment]
Ansible-2.9 has been released. Closing this as fixed at this point and will open a separate issue for 2.9
