### ISSUE TITLE
change image store location in grails3 version of image-service

### ISSUE THREAD

**Issue by shahmanash** [AtlasOfLivingAustralia/ala-install#303]
For the grails3 version of image-service , the image store folder should probably be changed.

https://github.com/AtlasOfLivingAustralia/ala-install/blob/feature/image-service-grails3/ansible/roles/image-service/tasks/main.yml#L52

```
alias: "{{ data_dir }}/images/store" 
```
should probably be 
```
alias: "{{ data_dir }}/image-service/store"
```

**Comment by djtfmartin** [comment]
thanks @shahmanash this was done.
