### ISSUE TITLE
Fix elasticsearch7 role

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/ala-install#344]
The elasticsearch7 role was added as an invalid git submodule in this commit.

https://github.com/AtlasOfLivingAustralia/ala-install/commit/5026c02254765280ab40fa5717cc084fe324d420

**Comment by djtfmartin** [comment]
I think this is fixed. Ive removed the git submodule, and image-service is now using the `ansible-elasticsearch` role added by @chrisala
