### ISSUE TITLE
Upgrade ansible supported version to 2.9

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/ala-install#355]
Ansible-2.9 was released recently. This issue is to track testing for it and fixes for any regressions before switching it on as the default.

- [x] Notify in Slack channels that this will be occurring on Wednesday 5 May/Thursday 6 May
- [x] Switch readme over to ansible-2.9
- [x] Switch required ansible version to 2.9
- [x] Switch ansible version on test server to 2.9

**Comment by ansell** [comment]
@vjrj This swtich to Ansible-2.9 will be implemented on Wednesday 5 May/Thursday 6 May

**Comment by vjrj** [comment]
@ansell thanks for the information

**Comment by vjrj** [comment]
I tested 5 roles so far with `2.9.6` and worked well.

**Comment by ansell** [comment]
Installs using 2.9.7 seem to be working currently. Will open separate issues for bugs that appear.
