### ISSUE TITLE
create images databse

### ISSUE THREAD

**Issue by kantobogy** [AtlasOfLivingAustralia/ala-install#356]
After execute
#> ansible-playbook -i inventories/vagrant/demo-vagrant ala-demo.yml --private-key ~/.vagrant.d/insecure_private_key --user vagrant --become

the fatal error is:
fatal: [vagrant1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'image_service_db_name' is undefined\n\nThe error appears to be in '/home/leonardo/Downloads/ala-install/ansible/roles/image-service/tasks/main.yml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: create images database\n  ^ here\n"}

**Comment by ansell** [comment]
@kantobogy I patched the variable names which had changed recently, can you test again after pulling the latest commit?

**Comment by vjrj** [comment]
I'm doing the same with `ansible/inventories/living-atlas` but didn't have time yesterday to pull. In some minutes...

**Comment by ansell** [comment]
This should be fixed, reopen if it is still an issue.
