### ISSUE TITLE
AnsibleUndefinedVariable (bie-hub- speciesList_api_key)

### ISSUE THREAD

**Issue by kantobogy** [AtlasOfLivingAustralia/ala-install#357]
Dear all

After execute
#> ansible-playbook -i inventories/vagrant/demo-vagrant ala-demo.yml --private-key ~/.vagrant.d/insecure_private_key --user vagrant --become

TASK [bie-hub : copy all config.properties] *******************************************************************************************************************************
fatal: [vagrant1]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'speciesList_api_key' is undefined"}

Thanks in advanced

**Comment by vjrj** [comment]
Hi @kantobogy I just send a PR with some updated inventories. 

This var was added some days ago. you can simple put some value:
https://github.com/AtlasOfLivingAustralia/ala-install/pull/358/files#diff-a2e1c7737b7f7677e82c8068f08acb2eR273

**Comment by vjrj** [comment]
I also updated the generator similarly:
https://github.com/living-atlases/generator-living-atlas/commit/3bca30df7dae7632ef9f1bb6afa31dc6ce3999ed

**Comment by louiepang** [comment]
hi All,

I still have the fatal exception even checked the speciesList_api_key existed.
I tried to export from environment before run the  ansible-playbook but the result is same.

Any further idea that I can verify for my installation?

**Comment by vjrj** [comment]
Hi @louiepang see this inventory sample:
https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/inventories/living-atlas#L273
did you added the var like this?

If you problem persist, do you have access to our slack channel to contact me via DM so I try to help you there?

**Comment by vjrj** [comment]
I tested several times ala-install without this problem.
