### ISSUE TITLE
Missing dependencies 'psycopg2 installing images in Ubuntu 18.10

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/ala-install#372]
We just get this error trying to install images-service in a brand new server:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No  module named 'psycopg2'                                                                                                
fatal: [imagenes.snib.conap.gob.gt]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (psycopg2) on cass's Python /usr/bin/python3. Please read module documentation and install in the appropriate location"}RUNNING HANDLER [postgresql : restart postgresql] **********************************************************************
PLAY RECAP *************************************************************************************************************│·····················································································································
imagenes.snib.conap.gob.gt : ok=111  changed=27   unreachable=0    failed=1    skipped=195  rescued=0    ignored=0   
```

Installing `python3-psycopg2` solved the issue.

**Comment by ansell** [comment]
We won't be supporting Ubuntu-18.10 (which is already EoL), however, this will likely also show up on Ubuntu-20.04 that is two months away from release and which we will support.

If you can make up a pull request I will review and merge it.

**Comment by vjrj** [comment]
`gpg` is also a dependency that is missing in the image service role.
```
fatal: [images.tanbif.ditnet.ac.tz]: FAILED! => {"changed": false, "msg": "Failed to find required executable gpg in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"}
```
Just discovered installing Tanzania's testing server.

**Comment by vjrj** [comment]
Also we had to install `python3-lxml`.

**Comment by vjrj** [comment]
I just realized that they are using 18.04 so the 'python3-lxml' and 'gpg' dependencies are missing. So forget my last comments.

**Comment by ansell** [comment]
Just clarifying, we need to add `python3-psycopg2` as a python dependency to get `image-service` working on `Ubuntu-18.04`. The issue title still says `18.10`.

**Comment by vjrj** [comment]
Sorry, it's my fault. I just realized that in Guatemala is running also 18.04 as in Tanzania. So I think we can close this issue.
