### ISSUE TITLE
repo.boundlessgeo.com for geoserver war is unnaccessible 

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/ala-install#384]
I found this error running spatial playbook:
```
fatal: [spatial.canadensys.net]: FAILED! => {"changed": false, "msg": "Failed to connect to repo.boundlessgeo.com at port 443: [Errno -2] Name or service not known", "status": -1, "url": "https://repo.boundlessgeo.com/main/org/geoserver/web/gs-web-app/2.14.1/gs-web-app-2.14.1.war"}
```
It seems that another possible location for this war is: 
http://sourceforge.net/projects/geoserver/files/GeoServer/2.14.1/geoserver-2.14.1-war.zip
(but it's zipped).

**Comment by ansell** [comment]
The replacement may be repo.osgeo.org based on https://osgeo-org.atlassian.net/browse/GEOS-9566

https://repo.osgeo.org/repository/release/org/geoserver/web/gs-web-app/2.14.1/gs-web-app-2.14.1.war

**Comment by ansell** [comment]
For reference, the migration process for anyone who has separate Maven repository issues as a result of this (as I imagine I will myself) is at: 

https://github.com/geotools/geotools/wiki/Change-from-webdav-to-nexus-repository

**Comment by vjrj** [comment]
With the url https://repo.osgeo.org/repository/release/org/geoserver/web/gs-web-app/2.14.1/gs-web-app-2.14.1.war
the role works.

Thanks @ansell !
