### ISSUE TITLE
ansible error due to ansible/inventories/vagrant/_README

### ISSUE THREAD

**Issue by niconoe** [AtlasOfLivingAustralia/ala-install#40]
Hi,

Due to the presence of ansible/inventories/vagrant/_README, I get an error (ERROR: Invalid ini entry: directory - need more than 1 value to unpack) when running:

    ansible-playbook -i inventories/vagrant ala-demo.yml --private-key ~/.vagrant.d/insecure_private_key -u root

I guess this is similar to the problem discussed at: https://github.com/ansible/ansible/issues/9523. Anyway, this works once I manually remove the _README file. But you may want to update the documentation or the directory.

I use Ansible 1.8.4 on OS X Yosemite.

**Comment by m-r-c** [comment]
I have moved the content of the _README file to ansible/README.md and deleted the _README file.
