### ISSUE TITLE
Small inconsistency in README

### ISSUE THREAD

**Issue by niconoe** [AtlasOfLivingAustralia/ala-install#41]
If I'm not mistaken, point 1.Vagrant gives instructions to install the Ubuntu VM, but the first ansible-playbook command to appear (ansible-playbook -i inventories/vagrant ala-demo.yml --private-key ~/.vagrant.d/insecure_private_key -u root) seems to be targeting Centos VM.

Maybe it's just me, but given the beginning of the tutorial I was having the impression that Ubuntu was the "default/preferred" environment, but it seems wrong later (unable to run ansible  scripts for Ubuntu, but CentOS seems better).

If keeping two versions perfectly is tedious, maybe it's better if the tutorial explicitly focus on only one VM ?

**Comment by djtfmartin** [comment]
Thanks. I agree. The ALA use Ubuntu VMs for development and production. 
We aren't maintaining the CentOS versions too well because of our bias to Ubuntu. We should change the README to reflect this.

**Comment by niconoe** [comment]
Thanks, good to know that Ubuntu is the way to go! I however so far encounter a few troubles to run the Ansible scripts (following the tutorial) on Ubuntu, so I may fill other issues !

Best,

**Comment by djtfmartin** [comment]
Fixed by @timrobertson100 in 04bb6a98210536a2b37651a2201e92a573585983
