### ISSUE TITLE
Error running demo-vagrant ansible

### ISSUE THREAD

**Issue by PaulKiddle** [AtlasOfLivingAustralia/ala-install#419]
Following the instructions for setting up demo vagrant instance, I encounter the following error when running ansible:

```
TASK [nginx : Check if vhost fragments directory variable is specified or warning is overriden] ***
fatal: [vagrant1]: FAILED! => {"changed": false, "msg": "The variable 'nginx_vhost_fragments_to_clear' must be defined and not empty or nginx_vhost_fragments_to_clear_no_warning=True"}
```

Please update the code to fix this, or add to the README instructions on how to avoid this.

**Comment by vjrj** [comment]
Hi @PaulKiddle it seems that this relative new variable is missing in the ansible vagrant inventory you are using. I other test inventories looks like this:

```
ansible/inventories/living-atlas-2020:nginx_vhost_fragments_to_clear = ["living-atlas.org","auth.living-atlas.org","spatial.living-atlas.org"]
ansible/inventories/living-atlas:nginx_vhost_fragments_to_clear = ["living-atlas.org","auth.living-atlas.org","spatial.living-atlas.org"]
ansible/inventories/vagrant/ecodata-vagrant:nginx_vhost_fragments_to_clear=["ecodata.vagrant1.ala.org.au"]
ansible/inventories/vagrant/ecodata-vagrant-grails2:nginx_vhost_fragments_to_clear=["ecodata.vagrant1.ala.org.au"]
ansible/inventories/vagrant/image-service-vagrant:nginx_vhost_fragments_to_clear = ["images.vagrant1.ala.org.au"]
ansible/inventories/workshop/demo-livingatlas.yml:nginx_vhost_fragments_to_clear=["demo.livingatlas.org"]
```
While we correct this missing variable, I added a recent explanation @ansell did in our documentation wiki:
https://github.com/AtlasOfLivingAustralia/documentation/wiki/Troubleshooting#nginx

I also recommend you:
https://github.com/AtlasOfLivingAustralia/documentation/wiki/LA-Quick-Start-Guide

If you want to generate some production ready ansible inventories that you can test in some demo VMs, I recommend also to have a look:
https://www.npmjs.com/package/generator-living-atlas

With any additional problem, don't hesitate to add any other issue or contact us in our slack channel (just ask for an slack invitation to our community channel).

**Comment by vjrj** [comment]
I've just sent and PR. If you are using the demo inventory, sometihing like this should work: https://github.com/AtlasOfLivingAustralia/ala-install/pull/420/files#diff-b0042a1a19416149c5c1c6d617f32c32

**Comment by vjrj** [comment]
I think this is fixed now.

**Comment by PaulKiddle** [comment]
Hi @vjrj, thanks for your responses. Who can I ask for an invitation to the community slack channel?

**Comment by vjrj** [comment]
Off course, can I use your email in https://www.mrkiddle.co.uk/ ?

**Comment by PaulKiddle** [comment]
Please can you use p.kiddle@nhm.ac.uk

**Comment by ansell** [comment]
@PaulKiddle I have sent you an invite for the Slack channel.
