### ISSUE TITLE
logger service nginx vhost add an extra comma and nginx fails to reload

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/ala-install#423]
After the last changes in the logger role, the nginx vhost add an extra comma in the vhost of a test service:
``` 
    location /logger/service/logger {
        if ($blocked_ip) {
            return 403;
        }
        if ($blocked_user_agent) {
            return 444;
        }
        access_log /var/log/nginx/access.log main;
        ; # THIS ONE
        # proxy_set_header Host $host;
```
The log:
```
sep 08 21:04:27 vm7 nginx[15098]: nginx: [emerg] unexpected ";" in /etc/nginx/sites-enabled/sibad.l-a.site-logger-service.conf:136
```

It seems is after this line added recently by @ansell 
https://github.com/AtlasOfLivingAustralia/ala-install/blob/88c3ea16d219580e3546ef2b42734d86d2989583/ansible/roles/nginx_vhost/templates/fragment_73_location.j2#L12

**Comment by ansell** [comment]
Thanks, I will look into that. It is the line for logging HTTP POST Request Bodies, which is disabled by default and that semi-colon should not be there by default.

**Comment by ansell** [comment]
@vjrj I am not sure what may have happened, but you don't seem to be using the `master` branch, where this is fixed:

https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/nginx_vhost/templates/fragment_73_location.j2#L14

**Comment by vjrj** [comment]
You are right @ansell. 

I'm reviewing `27_pipelines_spark_hadoop` that doesn't have this fix.

I've just tested again and the vhost is configured properly with `master`.
