### ISSUE TITLE
A few more comments for README

### ISSUE THREAD

**Issue by niconoe** [AtlasOfLivingAustralia/ala-install#45]
Hi again,

Wouldn't it be good to conclude the tutorial with some something in the like of "That's ready! You can now access your ala instance at ```http://demo.vagrant1.ala.org.au/```
 ?

Also, the tutorial asks to add ```10.1.1.2 vagrant1 vagrant1.ala.org.au```to /etc/hosts. But:
* On my machine at least, I add to change it to ```10.1.1.2 vagrant1 demo.vagrant1.ala.org.au```
* the hosts file is not always at /etc/hosts (/private/etc/hosts on recent Mac OS X for example)

I think such small fixes to the doc would make the tasks easier for newcomers ! Best, n.

**Comment by djtfmartin** [comment]
Thats for these suggestions. The second half of this issue was tackled here:

https://github.com/AtlasOfLivingAustralia/ala-install/issues/54

Thanks again!
