### ISSUE TITLE
Use Ansible-2.10

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/ala-install#450]
Ansible-2.10 has been released and has had a few patch versions to iron out the initial bugs. We should bump to using it if there are no critical bugs with it.

@vjrj Can you upgrade locally and run some tests to verify it works well for you and then we can set a date for the switchover?

**Comment by vjrj** [comment]
I tested the main services and worked for me but I've tested with `2.10.0` (sorry I didn't notice your branch and commit). Re-testing with `2.10.3`.

**Comment by vjrj** [comment]
Worked also with `2.10.3`.

**Comment by ansell** [comment]
Thanks, I will propose a date in Slack for switching over.

**Comment by ansell** [comment]
This has been committed, so closing. Any bugs that come up are probably easiest to create separate issues for rather than reopening this issue.
