### ISSUE TITLE
Ansible failed - ALA Demo on Ubuntu 18

### ISSUE THREAD

**Issue by DMarinuks** [AtlasOfLivingAustralia/ala-install#465]
Hello,

I am trying to start ALA demo 2020 with ansible-playbook on Ubuntu 18 machine, but it is not working. 
First, mysql server package was not found, which I could fix, but now it fails to start solr7.
Ubunvtu VM has 8 CPU and 16 GB RAM.
Could you perhaps tell me if I am doing something wrong or what should I do to start ALA demo?

Thank you!

**Comment by vjrj** [comment]
The demo2020 is for testing the ubuntu 20.04 transition.
Can you try to use some inventories generated from here:
https://generator.l-a.site/
Also you can read this:
https://github.com/AtlasOfLivingAustralia/documentation/wiki/LA-Quick-Start-Guide
if you have any further problem, don't hesitate to contact me/us. Also if you want, we can invite you to our slack channel to get more support.

**Comment by DMarinuks** [comment]
Thank you for a quick reply and sorry for the delayed response.

The playbook for LA 2020 demo was executed without any errors and I can see the Living Atlas Demo landing page with links, however, none of the links are working, when I click on the Data registry links, like collections browser, web services, Admin interface, I get 404 from Nginx. I had a look and my /srv/living-atlas.org/www/ folder does not have any collectory folder in it. All other links also return 404.

Did I miss something?

**Comment by vjrj** [comment]
`404` many times means that tomcat doesn't started for any reason. The web proxy is configured but cannot find the services running in tomcat.

To understand the source of you errors have a look to:
https://github.com/AtlasOfLivingAustralia/documentation/wiki/Troubleshooting#basic-service-checks-is-tomcatsolrcassandraapachecasmysqlwhatever-running-correctly
and also:
https://github.com/AtlasOfLivingAustralia/documentation/wiki/Logs-location

**Comment by DMarinuks** [comment]
It seems that tomcat9 can not connect to MySQL.   
Mysql is running without errors.

**Comment by vjrj** [comment]
Hi @DMarinuks . 

As I mentioned before, I do not recommend to use that demo-2020 inventory yet (it's only there for testing Ubuntu 20.04 servers and services).

I recommend to use a 18.04 server/s (as the one your are using) with:
- the https://github.com/AtlasOfLivingAustralia/ala-install/tree/master/ansible/inventories/workshop inventories
- or even better some inventories generated with https://generator.l-a.site/ if you are looking for some production ready inventories (like the one we use in several countries).

These inventories that I recommend still use `tomcat8`.
