### ISSUE TITLE
mysql common role vs mysql-server role

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/ala-install#485]
After a conversation with @matthewandrews and looking forward an ubuntu 20.04 upgrade I created a [generic mysql role](https://github.com/AtlasOfLivingAustralia/ala-install/pull/472) based in the common role with the same pattern that other generic roles like `tomcat` or `java`. I tested with `u18.04` and `u20.04` servers.

As summary we were using `mysql` role in general except for some old playbooks I didn't tested that were using still a `mysql-legacy` role. So these old playbooks was not affected with the new `mysql` role.

Recently I noticed that @Rita-C started to use another more simple `mysql-server` role in `webapi` and `cas` services. Rita, can we use `mysql` role instead? Did you find some problem with it?

**Comment by vjrj** [comment]
Sorry again, @Rita-C but trying to install CAS I'm getting this error with this introduced `mysql-server` role:

```
TASK [mysql-5.7 : change root user password on first run] **************************************************************
failed: [vt-2.l-a.site] (item=vt-2) => {"ansible_loop_var": "item", "changed": false, "item": "vt-2", "msg": "The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required."}
failed: [vt-2.l-a.site] (item=127.0.0.1) => {"ansible_loop_var": "item", "changed": false, "item": "127.0.0.1", "msg": "The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required."}
failed: [vt-2.l-a.site] (item=::1) => {"ansible_loop_var": "item", "changed": false, "item": "::1", "msg": "The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required."}
failed: [vt-2.l-a.site] (item=localhost) => {"ansible_loop_var": "item", "changed": false, "item": "localhost", "msg": "The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required."}

RUNNING HANDLER [mysql-5.7 : restart mysql] ****************************************************************************

PLAY RECAP *************************************************************************************************************
vt-2.l-a.site              : ok=64   changed=4    unreachable=0    failed=1    skipped=93   rescued=0    ignored=0 
```

**Comment by Rita-C** [comment]
Hi @vjrj ,
Sorry didn't fully test this yet.
Just compared `mysql-server` with `mysql` tasks/main.yml, `mysql-server` contains:
```
- name: Install mysql-server 8.0 for Ubuntu 20.04
  include_role: name=mysql-8.0
  when: ansible_os_family == "Debian" and ansible_distribution_version == "20.04"
  tags: mysql-server
```

`mysql` does NOT have.

**Comment by Rita-C** [comment]
Hi @vjrj ,
Thanks for quoting `setfacts`. 
The `mysql-server` role was introduced to webapi by PA, it was suggested to me when the original `mysql` failed on CAS deployment.
A common role sounds good.

**Comment by Rita-C** [comment]
Updated `cas5-standalone` to use mysql role.

**Comment by vjrj** [comment]
Thanks indeed @Rita-C . If I can help tuning/testing this role better just write me.
