### ISSUE TITLE
bie_search_path in undefined

### ISSUE THREAD

**Issue by niconoe** [AtlasOfLivingAustralia/ala-install#52]
Hi,

I'm trying to install via the standard vagrant/ansible scripts (Ubuntu in Virtualbox), and ansible fails with the following error:

    TASK: [biocache-hub | copy all config.properties] *****************************
    fatal: [vagrant1] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables:       'bie_search_path' is undefined", 'failed': True}
    fatal: [vagrant1] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'bie_search_path' is undefined", 'failed': True}

Any idea of where could be my mistake ?

**Comment by djtfmartin** [comment]
Thanks Nicolas.

Thats a bit of a bug. Those properties should have a default.

if you add the following to your inventory, this should get you passed the error for now:

bie_search_path=
bie_base_url=


________________________________
