### ISSUE TITLE
spatial-hub >= 1.0.0 installation?

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/ala-install#533]
We see that from `spatial` version 1.0.0 now the artifact in a `jar,` not a war, so `ala-install` fails trying to deploy it with a `404` as tries to download a `war`:

![image](https://user-images.githubusercontent.com/180085/147330282-4e90cbe3-2bdf-4edb-8e2d-827bfa0b8331.png)

How ALA is installing this new versions?

cc @qifeng-bai and @ @Meshack007 

TIA

**Comment by qifeng-bai** [comment]
@vjrj We have 1.0.1, but it is also a jar.  I am checking on that

**Comment by vjrj** [comment]
Thanks @qifeng-bai. I see that `1.0.1` has a war. Closing this.
