### ISSUE TITLE
Problems with MySQL and ansible 2.0 and 1.9.x

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/ala-install#56]
Problems with MySQL and ansible 2.0 and 1.9.x

This was noted by a few developers at the workshop in Paris. The role that caused the problem was the MySQL role.

**Comment by sadeghim** [comment]
Installed ala-demo with ansible version 2.0.1.0 on ubuntu without any error. Please close the issue if you think it's resolved.

**Comment by m-r-c** [comment]
To be investigated as part of the ansible version standardization and testing work.

**Comment by m-r-c** [comment]
I have run the ala-demo and specieslist playbooks (both use the mysql role) with Ansible 2.0.1.0, and cannot see any obvious issues. MySql installs correctly, the databases are successfully created and all the config (there isn't much that is done by the ansible role) appears correct. I have also run the playbooks multiple times to ensure they are idempotent, with no issues. Using the ala-demo Collectory, I can successfully create new records, so permissions appear to be ok.

Running the scripts against our ubuntu 14.10 vagrantfile installs version ```mysql  Ver 14.14 Distrib 5.6.22, for osx10.10 (x86_64) using  EditLine wrapper```.

Closing for now - new can be raised if anything else comes up.
