### ISSUE TITLE
Missing pipelines jenkins job

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/ala-install#582]
This [Export-Cassandra-to-DwCA pipelines job](
https://github.com/AtlasOfLivingAustralia/ala-install/blob/5282e0c7cc41cdc69b928acd98c7ff4bb5661f26/ansible/roles/pipelines_jenkins/templates/jenkins/jobs/Full-migration/config.xml.j2#L11) in ala-install is missing. Can you @djtfmartin or any other ALA member commit to ala-install? It does not matter if it has ALA server names.

**Comment by djtfmartin** [comment]
@vjrj  - ive just sent via slack
