### ISSUE TITLE
image-service deploy returns 404 since last commits 

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/ala-install#597]
Hi @yasima-csiro since [this commit](https://github.com/AtlasOfLivingAustralia/ala-install/commit/077be9d73c3f55cabb29a7d40000fa42d0861a16) we are getting this error:

```
TASK [exec-jar : Download image-service JAR] ***********************************
Tuesday 12 July 2022  14:37:39 +0200 (0:00:00.758)       0:04:58.620 ********** 
fatal: [ala-install-test-2]: FAILED! => {"changed": false, "msg": "Failed to download artifact au.org.ala:image-service:war:exec:1.1.7.1 because of HTTP Error 404: Not Foundfor URL [https://nexus.ala.org.au/content/groups/public/au/org/ala/image-service/1.1.7.1/image-service-1.1.7.1-exec.war"}](https://nexus.ala.org.au/content/groups/public/au/org/ala/image-service/1.1.7.1/image-service-1.1.7.1-exec.war%22%7D%1B[0m)
```

The change:

![image](https://user-images.githubusercontent.com/180085/178538205-ca085ab5-eb17-4624-a3bd-5189d529c36a.png)

If more recent versions of `1.1.7.1` need to use a `war` instead of a `jar` like before we can use a conditional like:
https://github.com/AtlasOfLivingAustralia/ala-install/blob/cf5948fb88cbd498a232100249aba03aa697bd09/ansible/roles/profile-service/tasks/main.yml#L3

The same (I think) with the doi-service that in the same commit you switched to war instead of jar:

![image](https://user-images.githubusercontent.com/180085/178537743-6f0b8399-0ded-4fd4-b6c2-2ff407a9844f.png)

And probably the same with the pg version checking the ubuntu version in the ansible facts:

![image](https://user-images.githubusercontent.com/180085/178539063-c6190f70-f653-47c5-bc1a-fbe5ef92c9a2.png)

[Other examples](https://github.com/AtlasOfLivingAustralia/ala-install/search?q=%22version+is+version%22) of using `version is` check.

Thanks.

**Comment by vjrj** [comment]
Yes, pg fails too:

![image](https://user-images.githubusercontent.com/180085/178551248-cd90042b-3247-4363-867e-56947347f142.png)

Maybe we can use the [common setfacts](https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/common/tasks/setfacts.yml) as we do with mysql, tomcat...

**Comment by yasima-csiro** [comment]
Thanks @vjrj . I will revert this change.

**Comment by yasima-csiro** [comment]
Fixed - https://github.com/AtlasOfLivingAustralia/ala-install/commit/19ab3d2be5f6192dee1157aa0df4c43df80bb2ce

**Comment by vjrj** [comment]
Thanks indeed for your fast response @yasima-csiro
