### ISSUE TITLE
Error while evaluating conditional: sds_enabled

### ISSUE THREAD

**Issue by niconoe** [AtlasOfLivingAustralia/ala-install#61]
Hi,

I'm trying to re-install the ALA demo with all default options (vagrant/virtualbox/ansible/ala-demo.yml), and I get the following error:

TASK: [biocache-properties | Download SDS layers] *****************************
fatal: [vagrant1] => error while evaluating conditional: sds_enabled

FATAL: all hosts have already failed -- aborting

**Comment by djtfmartin** [comment]
Thanks Nicolas. It needed a sds_enabled=false in the inventory (which should have been there).
