### ISSUE TITLE
Input file not found: biocache-config.properties

### ISSUE THREAD

**Issue by niconoe** [AtlasOfLivingAustralia/ala-install#62]
Hi, just running the stock ALA demo  and got: 

TASK: [biocache-service | copy all template configs] **************************
fatal: [vagrant1] => input file not found at /Users/nicolasnoe/ala-install/ansible/roles/biocache-service/templates/config/biocache-config.properties or /Users/nicolasnoe/ala-install/ansible/config/biocache-config.properties

It seems this file exists, but in another directory: roles/biocache-properties/templates

Could you help?

**Comment by djtfmartin** [comment]
thanks @niconoe. 

I have a fix for this on my fork. Im just doing a complete test on EC2.

Heres the updated file:

https://github.com/djtfmartin/ala-install/blob/master/ansible/roles/biocache-service/tasks/main.yml

**Comment by djtfmartin** [comment]
This is now fixed on the master. Thanks again @niconoe
