### ISSUE TITLE
nameindex: lucene index is not downloaded every time script is run

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/ala-install#64]
role: nameindex
task: Download lucene index

The above task does not download nameindex file every time script is run. Problematic when file exists in the directory form previous download. It needs force parameter to download it every time.
```
 force=yes.
```

**Comment by m-r-c** [comment]
I have made this configurable via your inventory, with a new property ```force_nameindex_download``` (default is false).
