### ISSUE TITLE
Generic hub doesn't work anymore after VM restart

### ISSUE THREAD

**Issue by niconoe** [AtlasOfLivingAustralia/ala-install#65]
Hi, I'm using the script against Vagrant/Virtualbox.

After first running the ansible script, the page at http://demo.vagrant1.ala.org.au/generic-hub/search#tab_simpleSearch (linked from the home page) works well.

But after running vagrant halt then vagrant up, that page is not accessible (Tomcat throws an error 404 for /generic-hub/WEB-INF/grails-app/views/error.jsp). Maybe this is a "secondary" error (primary error, but then error page not found). 

Is there anything I can do to help you debug that (log files?) ?

Cheers!

**Comment by djtfmartin** [comment]
I thought we tackled this problem with this commit

https://github.com/AtlasOfLivingAustralia/ala-install/commit/b20e7fd930e97de5f331c38bc2b3c840bf9702b2

can i confirm you are using the latest ansible scripts from the ala-install master branch ?

**Comment by niconoe** [comment]
I think so, but just to be 100% sure I destroyed the VM, did a git pull and restart the ansible scripts from scratch... I'll let you know!

**Comment by niconoe** [comment]
I just tried again with the very last versions of the ansible scripts, and:
- there's no problem after a vagrant suspend/resume cycle
- however, the error still appears after a vagrant halt/up cycle

I don't know if it is related to the commit referenced by @djtfmartin. There's no error running the ansible scripts and the app works fine first, but it doesn't "survive" a VM restart.

**Comment by niconoe** [comment]
Hi, this seems to be hostname-related:

I discovered the following errors in Tomcat logs.

2015-07-02 11:49:12,591 ERROR [WebServicesService]  Failed to get json from web service (http://demo.vagrant1.ala.org.au/biocache-service/occurrences/search?q=*%3A*&start=0&pageSize=0&sort=score&dir=asc&qc=&facets=collection_uid&facets=institution_uid&facets=data_resource_uid&facets=data_provider_uid&facets=type_status&facets=basis_of_record&facets=species_group&facets=loan_destination&facets=establishment_means&facets=state_conservation&facets=state&facets=ibra&facets=imcra&facets=cl966&facets=country&facets=cl959&flimit=-1). class java.net.SocketTimeoutException Read timed out, java.net.SocketTimeoutException: Read timed out

I confirmed that the `demo.vagrant1.ala.org.au` hostname was unknown. After editing /etc/hosts such as  `demo.vagrant1.ala.org.au` is resolved to 127.0.0.1, the error seems to have disappeared.

I don't know the best way to solve this ? Should Ansible create a more complete /etc/hosts file in the VM? Or maybe it's more flexible to configure generic-hub so that it queries its webservices on localhost ?

**Comment by m-r-c** [comment]
I have modified the apache_vhost role to add the host name to the /etc/hosts file (mapped to 127.0.0.1) for all Vagrant builds (i.e. where the ```is_vagrant``` property is truthy).

A previous change had been made to the ala-demo role to add this for any build - that change is still in place, but will be overwritten for vagrant builds.
