### ISSUE TITLE
jwt_client_id versus security.oidc.clientId 

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/ala-install#701]
I'm not sure if `security.oidc.clientId` and `jwt_client_id` are always the same, or they can be different.

In other words, if we should reuse variable names like @djtfmartin did in this branch: https://github.com/AtlasOfLivingAustralia/ala-install/commit/3a5411bc4ed4f35b27cb03e9ccebebf77734e7ce#diff-a1298dd188946a72c166897d4e28ecbbaab003b82e128cbd14fcb7be09b4024c 
or we should use different variable names like in https://github.com/AtlasOfLivingAustralia/ala-install/pull/699
```
egrep -r "jwt_client_id|jwt_secret" .                                       
./ansible/roles/image-service/templates/config/image-service-config.yml:{% if jwt_client_id is defined %}
./ansible/roles/image-service/templates/config/image-service-config.yml:    client-id: {{ jwt_client_id }}
./ansible/roles/image-service/templates/config/image-service-config.yml:    secret: {{ jwt_secret }}
./ansible/roles/species-list/templates/specieslist-webapp-config.properties:webservice.client-id={{ jwt_client_id }}
./ansible/roles/species-list/templates/specieslist-webapp-config.properties:webservice.client-secret={{ jwt_secret }}
```
Currently #699 is causing this error:
```
TASK [species-list : copy all config.properties] *******************************
Monday 09 October 2023  03:43:53 +0200 (0:00:00.633)       0:01:14.212 ******** 
fatal: [ala-install-test-1]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'jwt_client_id' is undefined"}
```
That suggest that we should adapt all our inventories. But if we reuse variables like in Dave's above patch, this adaptation is not necessary.

**Comment by joe-lipson** [comment]
I wasn't sure about `security.oidc.clientId` and `webservice.client-id` either, they were the same in the configs I looked at but I don't know the background or where these fit in which was my question raised in #699 

There are some large PRs #667 and [ansible-install #35](https://github.com/AtlasOfLivingAustralia/ansible-inventories/pull/35) that add these config values well. I've only recently looked at these in any detail, they use different variable names and in some cases different values for oidc and webservice IDs and secrets. There will be some conflicts here
