### ISSUE TITLE
/var/log/tomcat7/biocache-service.log deleted/reset; NEEDS to be archived/preserved

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ala-install#71]
_From @mbohun on February 23, 2015 1:11_

both **production** and test env **biocache-service log (and most likely other services)** ansible-playbook-s should make sure that `biocache-serice.log` (and all other important log files: tomcat, solr, etc.) are properly preserved/archived (i found out accidentally on the 2015-02-20 when the `/var/log/tomcat7/biocache-service.log` i was working with was deleted, resp. replaced/reset and all the existing log messages starting from early January 2015 were lost)

NOTE: it is very likely that this applies to all ALA production vm-s/services

_Copied from original issue: AtlasOfLivingAustralia/biocache-service#41_

**Comment by nickdos** [comment]
Ansible issue - moving

**Comment by m-r-c** [comment]
Done. By default, the tomcat_deploy role will back up a log file with the same name as the context path. If the log file name is different, then pass a ```log_filename``` property into the tomcat_deploy role.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/ala-install/review/AI-CR-2
