### ISSUE TITLE
collectory stopped working

### ISSUE THREAD

**Issue by gulfrazahmed** [AtlasOfLivingAustralia/ala-install#85]
Hi,

I have configured a ubuntu/trusty64 box on vagrant and want to play two books one by one, namely ala-demo.yml and volunteer-portal.yml. I ran them one by one. If i run ala-demo.yml first, all functions of http://demo.vagrant1.ala.org.au works including /collectory (admin pages etc.). But when i run volunteer-portal.yml next, the collectory section of ala-demo stops working and say resource not found:

http://demo.vagrant1.ala.org.au/collectory
message : /collectory
description : the requested resource is not available
Apache Tomcat/7.0.52 (Ubuntu)

Similarly if i play volunteer-portal.yml on a new machine it then works, but after playing ala-demo.yml it (the former) stops working

My question is that could we run both playbooks at once ?
If yes then is this expected for collectory section (only) stops working ?

What could be the solution for this. On my end if have checked:

/data/generic-collectory folder

/usr/share/tomcat7
/var/lib/tomcat7/webapps (found ROOT folder without ROOT.war file besides other ala demo folders (all with corresponding .war files); does this matter?):

/var/lib/tomcat7/webapps-volunteer.vagrant1.ala.org.au (found ROOT folder only with ROOT.war file)

Tried to edit /etc/tomcat7/server.xml and tried to add demo.vagrant1.ala.org.au host at bottom, but in vain.

Question is that why only collectory pages (on demo.vagrant1...) stops working after playing volunteer-portal.yml

Any help would be appreciated.

Regards,

Gul.

**Comment by gulfrazahmed** [comment]
no one ?

**Comment by djtfmartin** [comment]
Hi Gui, sorry for the slow response.

I wouldn't recommending running all the playbooks at a single VM.
The playbooks are intended to setup new clean machines with the contents of that particular playbook.

Does this make sense ?

This is how we use these playbooks in a production environment, with many virtual machines.

**Comment by gulfrazahmed** [comment]
thanks!

i would like to setup volunteer-portal on another VM than ala-demo's but using mysql. The yml file says postgresql in the list, if i change it to mysql then the it files not played properly :+1: 
=====


PLAY [volunteer-portal] *******************************************************

GATHERING FACTS ***************************************************************
ok: [volunteer]

TASK: [apache | Install Apache2 (RedHat)] *************************************
skipping: [volunteer]

TASK: [apache | Start Apache2 (RedHat)] ***************************************
skipping: [volunteer]

TASK: [apache | Install Apache2 (Debian)] *************************************
changed: [volunteer]

TASK: [apache | Enable mod_proxy_http (enables mod_proxy transitively)] *******
changed: [volunteer]

TASK: [apache | Enable mod_proxy_ajp] *****************************************
changed: [volunteer]
ERROR: change handler (restart apache) is not defined
=====

i also would like that volunteer portal use same mysql db as that of ala-demo. 

how the above two things possibe? any help would be appreciated !

thanks

Gul

**Comment by gulfrazahmed** [comment]
sorry for bold and huge size fonts..

**Comment by djtfmartin** [comment]
We havent tested the volunteer portal with MySQL.
Switching over to MySQL would require more work on the ansible scripts, and it may require some work on the webapplication (although we would hope this to be minimal.

If you are just testing the software at this stage, I would recommend just using the scripts as they are.

**Comment by gulfrazahmed** [comment]
thanks for quick response Martin!

**Comment by gulfrazahmed** [comment]
Hi Martin,

Is this possible that the volunteer portal if we setup on another VM, we could access it administration from local website ? there is a Log In link but it redirects to public site or this is something not possible ? (or this is what it expect to do?) does the volunteer-portal.yml plays a basic interface for the website on local VM and for CAS it redirects to public site ?

What is ala-demo and what is the relation to volunteer portal ?

sorry for newbie questions. thanks

**Comment by gulfrazahmed** [comment]
few more questions :+1: 

why this is necessary to involve vagrant, ansible for volunteer portal etc ? couldnt this be done without these and without VMs on a dedicated server ?

Is this possible that we able to run same portal as that of http://ala.org.au on our local system without VMs, ansible, vagrant etc. ?

thanks

**Comment by gulfrazahmed** [comment]
sorry for thumbsup icon

**Comment by djtfmartin** [comment]
Thanks Gui. Its worth pointing out our mailing list: http://lists.gbif.org/mailman/listinfo/ala-portal
If you have more questions (which are welcome!) then this is probably the best place.
For any bugs/issues then Github is the best places.

Is this possible that the volunteer portal if we setup on another VM, we could access it administration from local website ? 

I assume you mean you only want the administration part to be accessible on an intranet. 
This is possible but would require configuration with Apache which sits in front of Tomcat which is running the web application. 
By default the volunteer portal using CAS for authentication but you can disable this by specifying the following in /data/volunteer-portal/config/volunteer-portal-config.properties

```
security.cas.bypass=true
uriFilterPattern=
```

There are ansible playbooks available for setting up the CAS authentication stack but if you are just evaluating the volunteer portal I would just do the above for now.

The ALA site (http://www.ala.org.au) consists of a large number of components. The ala-demo playbook is an attempt to just setup some core components (i.e. a subset of the ALA) on a virtual machine for evaluation purposes.

ALA only uses Vagrant for testing and development of ansible playbooks on our laptops. You dont need vagrant to setup these components on your virtual machine(s).
We (ALA) deploys all our software using Ansible and this is the recommended way of setting up these components. Of course you could set these things up without ansible but you are likely to hit problems that the ansible playbooks fix, so its worth looking at the playbooks.

Its certainly possible to install any component of the ALA. We recommend setting up individual components on separate VMs as this makes things a lot easier operationally.

Hope this helps

**Comment by gulfrazahmed** [comment]
thanks, i have submitted for my subscription at that mailing list, i have more questions and will ask there .. hopefully someone or you would answer promptly / on your earliest

thanks Martin!

**Comment by gulfrazahmed** [comment]
while i await for your confirmation to add me in mailing list (isnt there a
forum where i could post my questions) ? could you please indicate what
problem it could be :

I setup another VM and want to setup the CAS authentication on it. However
playing the book an error being occurred :

========================
TASK: [cas2 | create user store DB user]
**************************************
ok: [vagrant1]

TASK: [cas2 | copy transient files to tmp (schemas etc)]
**********************
skipping: [vagrant1] => (item=schema.sql)
skipping: [vagrant1] => (item=sp_get_user_attributes.sql)

TASK: [cas2 | create schema, stored procs and reference data]
*****************
skipping: [vagrant1] => (item=/tmp/schema.sql)
skipping: [vagrant1] => (item=/tmp/sp_get_user_attributes.sql)

TASK: [cas2 | create ticket registry database]
********************************
ok: [vagrant1]

TASK: [cas2 | create ticket registry DB user]
*********************************
ok: [vagrant1]

TASK: [cas2 | ensure data directory exists]
***********************************
ok: [vagrant1]

TASK: [cas2 | copy all template configs]
**************************************
fatal: [vagrant1] => {'msg': "AnsibleUndefinedVariable: One or more
undefined variables: 'pac4j_callback_url' is undefined", 'failed': True}
fatal: [vagrant1] => {'msg': 'One or more items failed.', 'failed': True,
'changed': False, 'results': [{'msg': "AnsibleUndefinedVariable: One or
more undefined variables: 'pac4j_callback_url' is undefined", 'failed':
True}]}

FATAL: all hosts have already failed -- aborting

PLAY RECAP
********************************************************************
           to retry, use: --limit @/root/auth-standalone.retry

vagrant1                   : ok=62   changed=6    unreachable=1    failed=0



========================

The purpose of cas to setup is so that when we click on Log In link on
volunteer.vagrant1.ala.org.au (running on sparate vm) it will redirerct to
that URL instead of public one.

On the other-hand the inventory files in ansible/inventories/vagrant
directroy always enlisting these URLs at the bottom of each file :

auth_base_url=https://auth.ala.org.au

auth_cas_url=https://auth.ala.org.au/cas


Does it mean we can  not setup CAS locally/on vm/intranet ?

thanks,

gul

**Comment by gulfrazahmed** [comment]
sorry that my question posted here

**Comment by djtfmartin** [comment]
Thanks Gui. I assume you where using the [auth-vagrant](https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/inventories/vagrant/auth-vagrant) inventory.

There was a problem with missing variables. I've just pushed an update to this file which should fix this problem.

**Comment by gulfrazahmed** [comment]
Hi Martin,

Thanks. Since my request was not confirmed by list moderator i am ought to
respond from here.

I am now getting another error for facebook call back URL :

=================
TASK: [cas2 | copy all template configs]
**************************************
fatal: [vagrant1] => {'msg': "AnsibleUndefinedVariable: *One or more
undefined variables: 'pac4j_facebook_consumer_key' is undefined", 'failed':
True}*
fatal: [vagrant1] => {'msg': 'One or more items failed.', 'failed': True,
'changed': False, 'results': [{'msg': "AnsibleUndefinedVariable: One or
more undefined variables: 'pac4j_facebook_consumer_key' is undefined",
'failed': True}]}

FATAL: all hosts have already failed -- aborting

PLAY RECAP
********************************************************************
           to retry, use: --limit @/root/auth-standalone.retry

vagrant1                   : ok=68   changed=31   unreachable=1    failed=0

=================


I again git cloned the ala-install repo but same results.

Also you did not replied on this in previous mail :


============================
On the other-hand the inventory files in ansible/inventories/vagrant
directroy always enlisting these URLs at the bottom of each file :

auth_base_url=https://auth.ala.org.au

auth_cas_url=https://auth.ala.org.au/cas


Does it mean we can  not setup CAS locally/on vm/intranet ?
============================

Sorry for these questions, but i see following in auth-vagrant inventory
file, should this also be filled ? i just commenting them out :

==============================
#facebook
#pac4j_facebook_consumer_key=to_be_added
#pac4j_facebook_consumer_secret=to_be_added

# twitter
#pac4j_twitter_consumer_key=to_be_added
#pac4j_twitter_consumer_secret=to_be_added

# github
#pac4j_github_consumer_key=to_be_added
#pac4j_github_consumer_secret=to_be_added

# google
#pac4j_google_consumer_key=to_be_added
#pac4j_google_consumer_secret=to_be_added

# linkedin
#pac4j_linkedin_consumer_key=to_be_added
#pac4j_linkedin_consumer_secret=to_be_added

# windows live
#pac4j_windows_consumer_key=to_be_added
#pac4j_windows_consumer_secret=to_be_added

# yahoo OAuth and OpenID
#pac4j_yahoo_consumer_key=to_be_added--
#pac4j_yahoo_consumer_secret=to_be_added

# automatic registration ALA user password
*user_create_password=temp123456* *<-- didnt commented this out*

#
# SSL Configuration files
#
#ssl_certificate_server_dir=/path/to/ssl/files/on/target/server
#ssl_certificate_local_dir=/path/to/local/ssl/files/to/be/copied/to/server
#ssl_cert_file=
#ssl_key_file=
#ssl_chain_file=
==============================

A quick response would be appreciated.

Regards,

GuL

**Comment by djtfmartin** [comment]
Yes, you are getting that error because you have commented out those properties.

If you want authentication to work with facebook etc you'll need to get the require secrets & keys.

The values in the inventory will allow the install to complete.

**Comment by gulfrazahmed** [comment]
but what if we dont require them?

and what about other part of the question please

thanks

**Comment by djtfmartin** [comment]
For the installation to complete you need the properties. Perhaps we should look at the script to make them entirely optional. But for now, just leave in the placeholder values. All this means is that the installation should complete, but authentication via the oauth provider e.g. facebook will not work (because the it requires authentication details that you'll need to get from facebook).

Does it mean we can not setup CAS locally/on vm/intranet ?

No. You should be able to setup CAS locally or on a VM or on a intranet. This is what we have done without production systems using the exact same scripts but with a different inventory to the auth-vagrant inventory.

**Comment by gulfrazahmed** [comment]
okay, so that inventory is not provided in ala-install repo (which i git cloned) ? then where please ?

**Comment by djtfmartin** [comment]
I cant provide this as it contains our production passwords and secret keys which are tied to the ALA's website. 

But the inventory is the same file as auth-vagrant, but with different passwords and keys.

If you are just testing an install with vagrant, then auth-vagrant will suffice.

**Comment by djtfmartin** [comment]
Hi Gui - Im interested in your project plans. Would you be able to email some details at david.martin___at___csiro.au?

**Comment by djtfmartin** [comment]
Closing. @gulfrazahmed feel free to raise specific issues as they come up. thanks
