### ISSUE TITLE
Demo: Links on the initial Apache-served demo page all 404

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/ala-install#89]
All of the links on the initial landing page after installing the demo (presumably all to Tomcat applications) return 404 pages served by Apache.

Attempting to directly access the Tomcat applications using port 8080 doesn't work, as it redirects back to port 80 and then 404's.

I checked that Tomcat did indeed startup correctly using the log file, /var/log/tomcat7/catalina.out, and restarted both Tomcat (first), then Apache, but Apache is still serving 404 pages for the Tomcat applications.

**Comment by ansell** [comment]
The only mapping that appears to be enabled in the Apache HTTPD config files between HTTPD and Tomcat is to /logger-service, and it is working. The rest of the AJP mappings, to /collectory, etc., appear to simply be missing at this point.

There are two "VirtualHost *:80" mappings in /etc/apache2/sites-enabled/, which may also be an issue but I am unfamiliar with what happens if you have two mappings and one actually has ServerName enabled inside of it.

**Comment by m-r-c** [comment]
This seems to be caused by a bug in the apache_vhosts role, which is overriding previous ProxyPass directives. Logger-service happens to be the last step of the playbook. If you run the sandbox tags for example after the main playbook has finished, then the ProxyPass directive will be sandbox.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/ala-install/review/AI-CR-4
