### ISSUE TITLE
Standardise Ansible version

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/ala-install#97]
The README states v1.8 is required and that there are some problems with 1.9. However, some recent script changes rely on functionality introduced in 2.x

Suggest we standardise on the current stable version (2.0.1.0, which is what pip currently installs by default), and test each of the scripts against this version. 

Devs would be required to ensure they are using the same Ansible version.

**Comment by ansell** [comment]
CC issue#56 describing the only bug referenced specifically so far for MySQL and Ansible-2

**Comment by m-r-c** [comment]
Stalled until #100 is done

**Comment by m-r-c** [comment]
Jenkins jobs are underway.
ALA Install README updated.
Email sent to all ALA devs informing them of the change.
ALA Wiki updated.
Ansible jobs modified to check the version and warn if the user isn't running the supported version.
