### ISSUE TITLE
Improvements to nginx role/s

### ISSUE THREAD

**Issue by matthewandrews** [AtlasOfLivingAustralia/ala-install#98]
The nginx ansible role/s in ala-install would benefit from being rewritten to centralise common config and only require app roles to supply properties which vary between apps (more like the existing apache_vhost role).

**Comment by m-r-c** [comment]
Use the apache_vhost role as a template for what the nginx role needs to do.

The minimum requirements are:

* Support deploying applications as the root context on a vhost (e.g. profiles.ala.org.au/), or as a separate context on a vhost (e.g. auth.ala.org.au/userdetails, auth.ala.org.au/cas...)
* Support HTTPS and/or HTTP. If HTTPS only, then any requests to HTTP need to be redirected.
* Use AJP when passing requests to Tomcat
* Default to retrieving SSL files (cert etc) from SSLMate
* Have an option to copy SSL files from a local directory

The apache_vhost role supports all of the above, so use the same config properties. All of these options need to be driven from the inventory file.

The end result should be to have a simple include in the application role similar to the existing apache_vhost include (e.g. https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/profile-hub/tasks/main.yml#L72)

We'll also need to update the AnsibleSkeleton.groovy file to use the cleaned-up version.

**Comment by matthewandrews** [comment]
That sounds good.  Specifically re HTTPS cert paths, I guess it would be OK to default to /etc/sslmate/ but we should, of course, support a user specifying a different path on the server for HTTPS certs, as most of our overseas users would likely not be using SSLMate (but may well be using a different system for deploying HTTPS certs).  Likewise I guess we could default to our HTTPS cert filenames (*.ala.org.au.crt, etc) but allow an inventory to set as needed.  This is very similar to the existing apache_vhost behaviour (except that the path and filenames do not have those defaults).

**Comment by m-r-c** [comment]
To be honest, I'm not a fan of defaulting environment-specific variables like this - I'd rather see the build fail due to an undefined variable than have it assume the deployment is for a specific environment.

**Comment by matthewandrews** [comment]
Sure, I'd prefer that too.  Copying a few lines between inventory files should not be too burdensome.

**Comment by patkyn** [comment]
Revision: https://upsource.ala.org.au/ala-install/review/AI-CR-11
